# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AccountsGetResponse do
  @moduledoc """
  AccountsGetResponse defines the response schema for `/accounts/get` and `/accounts/balance/get`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :item,
    :request_id
  ]

  @type t :: %__MODULE__{
    :accounts => [ThePlaidAPI.Model.AccountBase.t],
    :item => ThePlaidAPI.Model.Item.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AccountsGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, ThePlaidAPI.Model.AccountBase, options)
    |> deserialize(:item, :struct, ThePlaidAPI.Model.Item, options)
  end
end

