# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AccountIdentity do
  @moduledoc """
  Identity information about an account
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :balances,
    :mask,
    :name,
    :official_name,
    :type,
    :subtype,
    :verification_status,
    :persistent_account_id,
    :owners
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :balances => ThePlaidAPI.Model.AccountBalance.t,
    :mask => String.t | nil,
    :name => String.t,
    :official_name => String.t | nil,
    :type => ThePlaidAPI.Model.AccountType.t,
    :subtype => ThePlaidAPI.Model.AccountSubtype.t | nil,
    :verification_status => String.t | nil,
    :persistent_account_id => String.t | nil,
    :owners => [ThePlaidAPI.Model.Owner.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AccountIdentity do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:balances, :struct, ThePlaidAPI.Model.AccountBalance, options)
    |> deserialize(:type, :struct, ThePlaidAPI.Model.AccountType, options)
    |> deserialize(:subtype, :struct, ThePlaidAPI.Model.AccountSubtype, options)
    |> deserialize(:owners, :list, ThePlaidAPI.Model.Owner, options)
  end
end

