# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Activity do
  @moduledoc """
  Describes a consent activity.
  """

  @derive [Poison.Encoder]
  defstruct [
    :activity,
    :initiated_date,
    :id,
    :initiator,
    :state,
    :target_application_id,
    :scopes
  ]

  @type t :: %__MODULE__{
    :activity => ThePlaidAPI.Model.ActivityType.t,
    :initiated_date => String.t,
    :id => String.t,
    :initiator => String.t,
    :state => ThePlaidAPI.Model.ActionState.t,
    :target_application_id => String.t | nil,
    :scopes => ThePlaidAPI.Model.ScopesNullable.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Activity do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:activity, :struct, ThePlaidAPI.Model.ActivityType, options)
    |> deserialize(:state, :struct, ThePlaidAPI.Model.ActionState, options)
    |> deserialize(:scopes, :struct, ThePlaidAPI.Model.ScopesNullable, options)
  end
end

