# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AddressMatchScore do
  @moduledoc """
  Score found by matching address provided by the API with the address on the account at the financial institution. The score can range from 0 to 100 where 100 is a perfect match and 0 is a no match. If the account contains multiple owners, the maximum match score is filled.
  """

  @derive [Poison.Encoder]
  defstruct [
    :score,
    :is_postal_code_match
  ]

  @type t :: %__MODULE__{
    :score => integer() | nil,
    :is_postal_code_match => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AddressMatchScore do
  def decode(value, _options) do
    value
  end
end

