# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ApplicationGetRequest do
  @moduledoc """
  ApplicationGetRequest defines the schema for `/application/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :application_id
  ]

  @type t :: %__MODULE__{
    :client_id => String.t,
    :secret => String.t,
    :application_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ApplicationGetRequest do
  def decode(value, _options) do
    value
  end
end

