# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AssetReportFilterResponse do
  @moduledoc """
  AssetReportFilterResponse defines the response schema for `/asset_report/filter`
  """

  @derive [Poison.Encoder]
  defstruct [
    :asset_report_token,
    :asset_report_id,
    :request_id
  ]

  @type t :: %__MODULE__{
    :asset_report_token => String.t,
    :asset_report_id => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AssetReportFilterResponse do
  def decode(value, _options) do
    value
  end
end

