# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AssetReportAuditCopyRemoveRequest do
  @moduledoc """
  AssetReportAuditCopyRemoveRequest defines the request schema for `/asset_report/audit_copy/remove`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :audit_copy_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :audit_copy_token => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AssetReportAuditCopyRemoveRequest do
  def decode(value, _options) do
    value
  end
end

