# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AssetReport do
  @moduledoc """
  An object representing an Asset Report
  """

  @derive [Poison.Encoder]
  defstruct [
    :asset_report_id,
    :client_report_id,
    :date_generated,
    :days_requested,
    :user,
    :items
  ]

  @type t :: %__MODULE__{
    :asset_report_id => String.t,
    :client_report_id => String.t | nil,
    :date_generated => DateTime.t,
    :days_requested => float(),
    :user => ThePlaidAPI.Model.AssetReportUser.t,
    :items => [ThePlaidAPI.Model.AssetReportItem.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AssetReport do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:user, :struct, ThePlaidAPI.Model.AssetReportUser, options)
    |> deserialize(:items, :list, ThePlaidAPI.Model.AssetReportItem, options)
  end
end

