# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AssetReportTransactionAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :date_transacted,
    :credit_category
  ]

  @type t :: %__MODULE__{
    :date_transacted => String.t | nil,
    :credit_category => ThePlaidAPI.Model.CreditCategory.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AssetReportTransactionAllOf do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:credit_category, :struct, ThePlaidAPI.Model.CreditCategory, options)
  end
end

