# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AuthGetNumbers do
  @moduledoc """
  An object containing identifying numbers used for making electronic transfers to and from the `accounts`. The identifying number type (ACH, EFT, IBAN, or BACS) used will depend on the country of the account. An account may have more than one number type. If a particular identifying number type is not used by any `accounts` for which data has been requested, the array for that type will be empty.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ach,
    :eft,
    :international,
    :bacs
  ]

  @type t :: %__MODULE__{
    :ach => [ThePlaidAPI.Model.NumbersAch.t],
    :eft => [ThePlaidAPI.Model.NumbersEft.t],
    :international => [ThePlaidAPI.Model.NumbersInternational.t],
    :bacs => [ThePlaidAPI.Model.NumbersBacs.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AuthGetNumbers do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ach, :list, ThePlaidAPI.Model.NumbersAch, options)
    |> deserialize(:eft, :list, ThePlaidAPI.Model.NumbersEft, options)
    |> deserialize(:international, :list, ThePlaidAPI.Model.NumbersInternational, options)
    |> deserialize(:bacs, :list, ThePlaidAPI.Model.NumbersBacs, options)
  end
end

