# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.AuthMetadata do
  @moduledoc """
  Metadata that captures information about the Auth features of an institution.
  """

  @derive [Poison.Encoder]
  defstruct [
    :supported_methods
  ]

  @type t :: %__MODULE__{
    :supported_methods => ThePlaidAPI.Model.AuthSupportedMethods.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.AuthMetadata do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:supported_methods, :struct, ThePlaidAPI.Model.AuthSupportedMethods, options)
  end
end

