# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.BankTransferListResponse do
  @moduledoc """
  Defines the response schema for `/bank_transfer/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :bank_transfers,
    :request_id
  ]

  @type t :: %__MODULE__{
    :bank_transfers => [ThePlaidAPI.Model.BankTransfer.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.BankTransferListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bank_transfers, :list, ThePlaidAPI.Model.BankTransfer, options)
  end
end

