# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.BankTransferBalance do
  @moduledoc """
  Information about the balance of a bank transfer
  """

  @derive [Poison.Encoder]
  defstruct [
    :available,
    :transactable
  ]

  @type t :: %__MODULE__{
    :available => String.t,
    :transactable => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.BankTransferBalance do
  def decode(value, _options) do
    value
  end
end

