# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.BankTransferCreateRequest do
  @moduledoc """
  Defines the request schema for `/bank_transfer/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :idempotency_key,
    :access_token,
    :account_id,
    :type,
    :network,
    :amount,
    :iso_currency_code,
    :description,
    :ach_class,
    :user,
    :custom_tag,
    :metadata,
    :origination_account_id
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :idempotency_key => String.t,
    :access_token => String.t,
    :account_id => String.t,
    :type => ThePlaidAPI.Model.BankTransferType.t,
    :network => ThePlaidAPI.Model.BankTransferNetwork.t,
    :amount => String.t,
    :iso_currency_code => String.t,
    :description => String.t,
    :ach_class => ThePlaidAPI.Model.AchClass.t | nil,
    :user => ThePlaidAPI.Model.BankTransferUser.t,
    :custom_tag => String.t | nil,
    :metadata => %{optional(String.t) => String.t} | nil,
    :origination_account_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.BankTransferCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.BankTransferType, options)
    |> deserialize(:network, :struct, ThePlaidAPI.Model.BankTransferNetwork, options)
    |> deserialize(:ach_class, :struct, ThePlaidAPI.Model.AchClass, options)
    |> deserialize(:user, :struct, ThePlaidAPI.Model.BankTransferUser, options)
  end
end

