# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Category do
  @moduledoc """
  Information describing a transaction category
  """

  @derive [Poison.Encoder]
  defstruct [
    :category_id,
    :group,
    :hierarchy
  ]

  @type t :: %__MODULE__{
    :category_id => String.t,
    :group => String.t,
    :hierarchy => [String.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Category do
  def decode(value, _options) do
    value
  end
end

