# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ClientProvidedTransactionLocation do
  @moduledoc """
  A representation of where a transaction took place.  Use this field to pass in structured location information you may have about your transactions. Providing location data is optional but can increase result quality. If you have unstructured location information, it may be appended to the `description` field.
  """

  @derive [Poison.Encoder]
  defstruct [
    :country,
    :region,
    :city,
    :address,
    :postal_code
  ]

  @type t :: %__MODULE__{
    :country => String.t | nil,
    :region => String.t | nil,
    :city => String.t | nil,
    :address => String.t | nil,
    :postal_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ClientProvidedTransactionLocation do
  def decode(value, _options) do
    value
  end
end

