# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ClientProvidedEnhancedTransaction do
  @moduledoc """
  A client-provided transaction that Plaid has enhanced.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :description,
    :amount,
    :iso_currency_code,
    :enhancements
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :description => String.t,
    :amount => float(),
    :iso_currency_code => String.t,
    :enhancements => ThePlaidAPI.Model.Enhancements.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ClientProvidedEnhancedTransaction do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:enhancements, :struct, ThePlaidAPI.Model.Enhancements, options)
  end
end

