# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ClientProvidedRawTransaction do
  @moduledoc """
  A client-provided transaction for Plaid to enhance.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :description,
    :amount,
    :iso_currency_code
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :description => String.t,
    :amount => float(),
    :iso_currency_code => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ClientProvidedRawTransaction do
  def decode(value, _options) do
    value
  end
end

