# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ConnectedApplication do
  @moduledoc """
  Describes the connected application for a particular end user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :application_id,
    :name,
    :display_name,
    :logo_url,
    :application_url,
    :reason_for_access,
    :created_at,
    :scopes
  ]

  @type t :: %__MODULE__{
    :application_id => String.t,
    :name => String.t,
    :display_name => String.t | nil,
    :logo_url => String.t | nil,
    :application_url => String.t | nil,
    :reason_for_access => String.t | nil,
    :created_at => Date.t,
    :scopes => ThePlaidAPI.Model.ScopesNullable.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ConnectedApplication do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:created_at, :date, nil, options)
    |> deserialize(:scopes, :struct, ThePlaidAPI.Model.ScopesNullable, options)
  end
end

