# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditPayStubEmployer do
  @moduledoc """
  Information about the employer on the pay stub.
  """

  @derive [Poison.Encoder]
  defstruct [
    :address,
    :name
  ]

  @type t :: %__MODULE__{
    :address => ThePlaidAPI.Model.CreditPayStubAddress.t,
    :name => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditPayStubEmployer do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:address, :struct, ThePlaidAPI.Model.CreditPayStubAddress, options)
  end
end

