# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditBankIncomeGetResponse do
  @moduledoc """
  CreditBankIncomeGetResponse defines the response schema for `/credit/bank_income/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :bank_income,
    :request_id
  ]

  @type t :: %__MODULE__{
    :bank_income => [ThePlaidAPI.Model.CreditBankIncome.t] | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditBankIncomeGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:bank_income, :list, ThePlaidAPI.Model.CreditBankIncome, options)
  end
end

