# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacPartyIndividualVoa24 do
  @moduledoc """
  Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
  """

  @derive [Poison.Encoder]
  defstruct [
    :NAME
  ]

  @type t :: %__MODULE__{
    :NAME => ThePlaidAPI.Model.CreditFreddieMacIndividualNameVoa24.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacPartyIndividualVoa24 do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:NAME, :struct, ThePlaidAPI.Model.CreditFreddieMacIndividualNameVoa24, options)
  end
end

