# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditPayrollIncomeRiskSignalsGetResponse do
  @moduledoc """
  CreditPayrollIncomeRiskSignalsGetRequest defines the response schema for `/beta/credit/payroll_income/risk_signals/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :items,
    :error,
    :request_id
  ]

  @type t :: %__MODULE__{
    :items => [ThePlaidAPI.Model.PayrollRiskSignalsItem.t],
    :error => ThePlaidAPI.Model.PlaidError.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditPayrollIncomeRiskSignalsGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:items, :list, ThePlaidAPI.Model.PayrollRiskSignalsItem, options)
    |> deserialize(:error, :struct, ThePlaidAPI.Model.PlaidError, options)
  end
end

