# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditPayStubEarnings do
  @moduledoc """
  An object representing both a breakdown of earnings on a pay stub and the total earnings.
  """

  @derive [Poison.Encoder]
  defstruct [
    :breakdown,
    :total
  ]

  @type t :: %__MODULE__{
    :breakdown => [ThePlaidAPI.Model.PayStubEarningsBreakdown.t],
    :total => ThePlaidAPI.Model.PayStubEarningsTotal.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditPayStubEarnings do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:breakdown, :list, ThePlaidAPI.Model.PayStubEarningsBreakdown, options)
    |> deserialize(:total, :struct, ThePlaidAPI.Model.PayStubEarningsTotal, options)
  end
end

