# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacAssetTransactionsVoa24 do
  @moduledoc """
  Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ASSET_TRANSACTION
  ]

  @type t :: %__MODULE__{
    :ASSET_TRANSACTION => [ThePlaidAPI.Model.CreditFreddieMacAssetTransactionVoa24.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacAssetTransactionsVoa24 do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ASSET_TRANSACTION, :list, ThePlaidAPI.Model.CreditFreddieMacAssetTransactionVoa24, options)
  end
end

