# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacReportsGetRequest do
  @moduledoc """
  CreditFreddieMacReportsGetRequest defines the request schema for `credit/asset_report/freddie_mac/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :audit_copy_token,
    :client_id,
    :secret
  ]

  @type t :: %__MODULE__{
    :audit_copy_token => String.t,
    :client_id => String.t | nil,
    :secret => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacReportsGetRequest do
  def decode(value, _options) do
    value
  end
end

