# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditBankIncomeGetRequestOptions do
  @moduledoc """
  An optional object for `/credit/bank_income/get` request options.
  """

  @derive [Poison.Encoder]
  defstruct [
    :count
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditBankIncomeGetRequestOptions do
  def decode(value, _options) do
    value
  end
end

