# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditSessionsGetResponse do
  @moduledoc """
  CreditSessionsGetResponse defines the response schema for `/credit/sessions/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :sessions,
    :request_id
  ]

  @type t :: %__MODULE__{
    :sessions => [ThePlaidAPI.Model.CreditSession.t] | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditSessionsGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:sessions, :list, ThePlaidAPI.Model.CreditSession, options)
  end
end

