# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditSession do
  @moduledoc """
  Metadata and results for a Link session
  """

  @derive [Poison.Encoder]
  defstruct [
    :link_session_id,
    :session_start_time,
    :results,
    :errors
  ]

  @type t :: %__MODULE__{
    :link_session_id => String.t | nil,
    :session_start_time => DateTime.t | nil,
    :results => ThePlaidAPI.Model.CreditSessionResults.t | nil,
    :errors => [ThePlaidAPI.Model.CreditSessionError.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditSession do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:results, :struct, ThePlaidAPI.Model.CreditSessionResults, options)
    |> deserialize(:errors, :list, ThePlaidAPI.Model.CreditSessionError, options)
  end
end

