# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacAssetDetailVoe25 do
  @moduledoc """
  Details about an asset.
  """

  @derive [Poison.Encoder]
  defstruct [
    :AssetUniqueIdentifier,
    :AssetAccountIdentifier,
    :AssetAsOfDate,
    :AssetDescription,
    :AssetType,
    :AssetTypeAdditionalDescription,
    :AssetDaysRequestedCount,
    :AssetOwnershipType
  ]

  @type t :: %__MODULE__{
    :AssetUniqueIdentifier => String.t,
    :AssetAccountIdentifier => String.t,
    :AssetAsOfDate => String.t,
    :AssetDescription => String.t | nil,
    :AssetType => ThePlaidAPI.Model.AssetType.t,
    :AssetTypeAdditionalDescription => String.t | nil,
    :AssetDaysRequestedCount => integer(),
    :AssetOwnershipType => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacAssetDetailVoe25 do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AssetType, :struct, ThePlaidAPI.Model.AssetType, options)
  end
end

