# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacAssetTransactionVoe25 do
  @moduledoc """
  An object representing...
  """

  @derive [Poison.Encoder]
  defstruct [
    :ASSET_TRANSACTION_DETAIL,
    :ASSET_TRANSACTION_DESCRIPTION
  ]

  @type t :: %__MODULE__{
    :ASSET_TRANSACTION_DETAIL => ThePlaidAPI.Model.CreditFreddieMacAssetTransactionDetailVoe25.t,
    :ASSET_TRANSACTION_DESCRIPTION => [ThePlaidAPI.Model.AssetTransactionDescription.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacAssetTransactionVoe25 do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ASSET_TRANSACTION_DETAIL, :struct, ThePlaidAPI.Model.CreditFreddieMacAssetTransactionDetailVoe25, options)
    |> deserialize(:ASSET_TRANSACTION_DESCRIPTION, :list, ThePlaidAPI.Model.AssetTransactionDescription, options)
  end
end

