# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditPayStubEmployee do
  @moduledoc """
  Data about the employee.
  """

  @derive [Poison.Encoder]
  defstruct [
    :address,
    :name,
    :marital_status,
    :taxpayer_id
  ]

  @type t :: %__MODULE__{
    :address => ThePlaidAPI.Model.CreditPayStubAddress.t,
    :name => String.t | nil,
    :marital_status => String.t | nil,
    :taxpayer_id => ThePlaidAPI.Model.PayStubTaxpayerId.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditPayStubEmployee do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:address, :struct, ThePlaidAPI.Model.CreditPayStubAddress, options)
    |> deserialize(:taxpayer_id, :struct, ThePlaidAPI.Model.PayStubTaxpayerId, options)
  end
end

