# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditEmploymentItem do
  @moduledoc """
  The object containing employment items.
  """

  @derive [Poison.Encoder]
  defstruct [
    :item_id,
    :employments,
    :employment_report_token
  ]

  @type t :: %__MODULE__{
    :item_id => String.t,
    :employments => [ThePlaidAPI.Model.CreditEmploymentVerification.t],
    :employment_report_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditEmploymentItem do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:employments, :list, ThePlaidAPI.Model.CreditEmploymentVerification, options)
  end
end

