# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditAuditCopyTokenUpdateResponse do
  @moduledoc """
  CreditAuditCopyTokenUpdateResponse defines the response schema for `/credit/audit_copy_token/update`
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :updated
  ]

  @type t :: %__MODULE__{
    :request_id => String.t,
    :updated => boolean()
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditAuditCopyTokenUpdateResponse do
  def decode(value, _options) do
    value
  end
end

