# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditBankIncomeTransaction do
  @moduledoc """
  The transactions data for the end user's income source(s).
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :date,
    :name,
    :original_description,
    :pending,
    :transaction_id,
    :check_number,
    :iso_currency_code,
    :unofficial_currency_code
  ]

  @type t :: %__MODULE__{
    :amount => float() | nil,
    :date => Date.t | nil,
    :name => String.t | nil,
    :original_description => String.t | nil,
    :pending => boolean() | nil,
    :transaction_id => String.t | nil,
    :check_number => String.t | nil,
    :iso_currency_code => String.t | nil,
    :unofficial_currency_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditBankIncomeTransaction do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end

