# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditBankEmploymentReport do
  @moduledoc """
  The report of the Bank Employment data for an end user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bank_employment_report_id,
    :generated_time,
    :days_requested,
    :items,
    :warnings
  ]

  @type t :: %__MODULE__{
    :bank_employment_report_id => String.t,
    :generated_time => DateTime.t,
    :days_requested => integer(),
    :items => [ThePlaidAPI.Model.CreditBankEmploymentItem.t],
    :warnings => [ThePlaidAPI.Model.CreditBankEmploymentWarning.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditBankEmploymentReport do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:items, :list, ThePlaidAPI.Model.CreditBankEmploymentItem, options)
    |> deserialize(:warnings, :list, ThePlaidAPI.Model.CreditBankEmploymentWarning, options)
  end
end

