# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditFreddieMacVerificationOfAssetResponseVoa24 do
  @moduledoc """
  Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ASSETS
  ]

  @type t :: %__MODULE__{
    :ASSETS => ThePlaidAPI.Model.CreditFreddieMacAssetsVoa24.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditFreddieMacVerificationOfAssetResponseVoa24 do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ASSETS, :struct, ThePlaidAPI.Model.CreditFreddieMacAssetsVoa24, options)
  end
end

