# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CreditPayrollIncomeRefreshRequestOptions do
  @moduledoc """
  An optional object for `/credit/payroll_income/refresh` request options.
  """

  @derive [Poison.Encoder]
  defstruct [
    :item_ids,
    :webhook
  ]

  @type t :: %__MODULE__{
    :item_ids => [String.t] | nil,
    :webhook => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CreditPayrollIncomeRefreshRequestOptions do
  def decode(value, _options) do
    value
  end
end

