# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.CustomerInitiatedReturnRisk do
  @moduledoc """
  The object contains a risk score and a risk tier that evaluate the transaction return risk of an unauthorized debit. Common return codes in this category include: \"R05\", \"R07\", \"R10\", \"R11\", \"R29\". These returns typically have a return time frame of up to 60 calendar days. During this period, the customer of financial institutions can dispute a transaction as unauthorized.
  """

  @derive [Poison.Encoder]
  defstruct [
    :score,
    :risk_tier
  ]

  @type t :: %__MODULE__{
    :score => integer(),
    :risk_tier => integer()
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.CustomerInitiatedReturnRisk do
  def decode(value, _options) do
    value
  end
end

