# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.DashboardUserListResponse do
  @moduledoc """
  Paginated list of dashboard users
  """

  @derive [Poison.Encoder]
  defstruct [
    :dashboard_users,
    :next_cursor,
    :request_id
  ]

  @type t :: %__MODULE__{
    :dashboard_users => [ThePlaidAPI.Model.DashboardUser.t],
    :next_cursor => String.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.DashboardUserListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:dashboard_users, :list, ThePlaidAPI.Model.DashboardUser, options)
  end
end

