# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Deductions do
  @moduledoc """
  An object with the deduction information found on a paystub.
  """

  @derive [Poison.Encoder]
  defstruct [
    :subtotals,
    :breakdown,
    :totals,
    :total
  ]

  @type t :: %__MODULE__{
    :subtotals => [ThePlaidAPI.Model.Total.t] | nil,
    :breakdown => [ThePlaidAPI.Model.DeductionsBreakdown.t],
    :totals => [ThePlaidAPI.Model.Total.t] | nil,
    :total => ThePlaidAPI.Model.DeductionsTotal.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Deductions do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:subtotals, :list, ThePlaidAPI.Model.Total, options)
    |> deserialize(:breakdown, :list, ThePlaidAPI.Model.DeductionsBreakdown, options)
    |> deserialize(:totals, :list, ThePlaidAPI.Model.Total, options)
    |> deserialize(:total, :struct, ThePlaidAPI.Model.DeductionsTotal, options)
  end
end

