# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.DocumentRiskSummary do
  @moduledoc """
  A summary across all risk signals associated with a document
  """

  @derive [Poison.Encoder]
  defstruct [
    :risk_score
  ]

  @type t :: %__MODULE__{
    :risk_score => float() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.DocumentRiskSummary do
  def decode(value, _options) do
    value
  end
end

