# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.DocumentaryVerification do
  @moduledoc """
  Data, images, analysis, and results from the `documentary_verification` step. This field will be `null` unless `steps.documentary_verification` has reached a terminal state of either `success` or `failed`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :documents
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :documents => [ThePlaidAPI.Model.DocumentaryVerificationDocument.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.DocumentaryVerification do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:documents, :list, ThePlaidAPI.Model.DocumentaryVerificationDocument, options)
  end
end

