# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.EarningsTotal do
  @moduledoc """
  An object representing both the current pay period and year to date amount for an earning category.
  """

  @derive [Poison.Encoder]
  defstruct [
    :current_amount,
    :current_pay,
    :ytd_pay,
    :hours,
    :iso_currency_code,
    :unofficial_currency_code,
    :ytd_amount
  ]

  @type t :: %__MODULE__{
    :current_amount => float() | nil,
    :current_pay => ThePlaidAPI.Model.Pay.t | nil,
    :ytd_pay => ThePlaidAPI.Model.Pay.t | nil,
    :hours => float() | nil,
    :iso_currency_code => String.t | nil,
    :unofficial_currency_code => String.t | nil,
    :ytd_amount => float() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.EarningsTotal do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:current_pay, :struct, ThePlaidAPI.Model.Pay, options)
    |> deserialize(:ytd_pay, :struct, ThePlaidAPI.Model.Pay, options)
  end
end

