# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.EmploymentVerification do
  @moduledoc """
  An object containing proof of employment data for an individual
  """

  @derive [Poison.Encoder]
  defstruct [
    :status,
    :start_date,
    :end_date,
    :employer,
    :title,
    :platform_ids
  ]

  @type t :: %__MODULE__{
    :status => ThePlaidAPI.Model.EmploymentVerificationStatus.t | nil,
    :start_date => Date.t | nil,
    :end_date => Date.t | nil,
    :employer => ThePlaidAPI.Model.EmployerVerification.t | nil,
    :title => String.t | nil,
    :platform_ids => ThePlaidAPI.Model.PlatformIds.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.EmploymentVerification do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:status, :struct, ThePlaidAPI.Model.EmploymentVerificationStatus, options)
    |> deserialize(:start_date, :date, nil, options)
    |> deserialize(:end_date, :date, nil, options)
    |> deserialize(:employer, :struct, ThePlaidAPI.Model.EmployerVerification, options)
    |> deserialize(:platform_ids, :struct, ThePlaidAPI.Model.PlatformIds, options)
  end
end

