# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Enrichments do
  @moduledoc """
  A grouping of the Plaid produced transaction enrichment fields.
  """

  @derive [Poison.Encoder]
  defstruct [
    :check_number,
    :counterparties,
    :entity_id,
    :legacy_category_id,
    :legacy_category,
    :location,
    :logo_url,
    :merchant_name,
    :payment_channel,
    :personal_finance_category,
    :personal_finance_category_icon_url,
    :recurrence,
    :website
  ]

  @type t :: %__MODULE__{
    :check_number => String.t | nil,
    :counterparties => [ThePlaidAPI.Model.Counterparty.t],
    :entity_id => String.t | nil,
    :legacy_category_id => String.t | nil,
    :legacy_category => [String.t] | nil,
    :location => ThePlaidAPI.Model.Location.t,
    :logo_url => String.t | nil,
    :merchant_name => String.t | nil,
    :payment_channel => ThePlaidAPI.Model.PaymentChannel.t,
    :personal_finance_category => ThePlaidAPI.Model.PersonalFinanceCategory.t | nil,
    :personal_finance_category_icon_url => String.t,
    :recurrence => ThePlaidAPI.Model.Recurrence.t | nil,
    :website => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Enrichments do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:counterparties, :list, ThePlaidAPI.Model.Counterparty, options)
    |> deserialize(:location, :struct, ThePlaidAPI.Model.Location, options)
    |> deserialize(:payment_channel, :struct, ThePlaidAPI.Model.PaymentChannel, options)
    |> deserialize(:personal_finance_category, :struct, ThePlaidAPI.Model.PersonalFinanceCategory, options)
    |> deserialize(:recurrence, :struct, ThePlaidAPI.Model.Recurrence, options)
  end
end

