# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.EntityScreeningHitPhoneNumbers do
  @moduledoc """
  Phone number information associated with the entity screening hit
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :phone_number
  ]

  @type t :: %__MODULE__{
    :type => ThePlaidAPI.Model.PhoneType.t,
    :phone_number => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.EntityScreeningHitPhoneNumbers do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.PhoneType, options)
  end
end

