# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.EntityScreeningHitAnalysis do
  @moduledoc """
  Analysis information describing why a screening hit matched the provided entity information
  """

  @derive [Poison.Encoder]
  defstruct [
    :documents,
    :email_addresses,
    :locations,
    :names,
    :phone_numbers,
    :urls,
    :search_terms_version
  ]

  @type t :: %__MODULE__{
    :documents => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :email_addresses => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :locations => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :names => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :phone_numbers => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :urls => ThePlaidAPI.Model.MatchSummaryCode.t | nil,
    :search_terms_version => float()
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.EntityScreeningHitAnalysis do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:documents, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
    |> deserialize(:email_addresses, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
    |> deserialize(:locations, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
    |> deserialize(:names, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
    |> deserialize(:phone_numbers, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
    |> deserialize(:urls, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
  end
end

