# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.FdxNotificationPayload do
  @moduledoc """
  Custom key-value pairs payload for a notification
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :idType,
    :customFields
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :idType => ThePlaidAPI.Model.FdxNotificationPayloadIdType.t | nil,
    :customFields => ThePlaidAPI.Model.FdxfiAttribute.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.FdxNotificationPayload do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:idType, :struct, ThePlaidAPI.Model.FdxNotificationPayloadIdType, options)
    |> deserialize(:customFields, :struct, ThePlaidAPI.Model.FdxfiAttribute, options)
  end
end

