# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.FdxHateoasLink do
  @moduledoc """
  REST application constraint (Hypermedia As The Engine Of Application State)
  """

  @derive [Poison.Encoder]
  defstruct [
    :href,
    :action,
    :rel,
    :types
  ]

  @type t :: %__MODULE__{
    :href => String.t,
    :action => ThePlaidAPI.Model.FdxHateoasLinkAction.t | nil,
    :rel => String.t | nil,
    :types => [ThePlaidAPI.Model.FdxContentTypes.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.FdxHateoasLink do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:action, :struct, ThePlaidAPI.Model.FdxHateoasLinkAction, options)
    |> deserialize(:types, :list, ThePlaidAPI.Model.FdxContentTypes, options)
  end
end

