# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.HealthIncident do
  @moduledoc """
  A status health incident
  """

  @derive [Poison.Encoder]
  defstruct [
    :start_date,
    :end_date,
    :title,
    :incident_updates
  ]

  @type t :: %__MODULE__{
    :start_date => DateTime.t,
    :end_date => DateTime.t | nil,
    :title => String.t,
    :incident_updates => [ThePlaidAPI.Model.IncidentUpdate.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.HealthIncident do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:incident_updates, :list, ThePlaidAPI.Model.IncidentUpdate, options)
  end
end

