# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.HistoricalBalance do
  @moduledoc """
  An object representing a balance held by an account in the past
  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :current,
    :iso_currency_code,
    :unofficial_currency_code
  ]

  @type t :: %__MODULE__{
    :date => Date.t,
    :current => float(),
    :iso_currency_code => String.t | nil,
    :unofficial_currency_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.HistoricalBalance do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date, :date, nil, options)
  end
end

