# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.HoldingsOverride do
  @moduledoc """
  Specify the holdings on the account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :institution_price,
    :institution_price_as_of,
    :cost_basis,
    :quantity,
    :currency,
    :security
  ]

  @type t :: %__MODULE__{
    :institution_price => float(),
    :institution_price_as_of => Date.t | nil,
    :cost_basis => float() | nil,
    :quantity => float(),
    :currency => String.t,
    :security => ThePlaidAPI.Model.SecurityOverride.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.HoldingsOverride do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:institution_price_as_of, :date, nil, options)
    |> deserialize(:security, :struct, ThePlaidAPI.Model.SecurityOverride, options)
  end
end

