# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Holding do
  @moduledoc """
  A securities holding at an institution.
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :security_id,
    :institution_price,
    :institution_price_as_of,
    :institution_price_datetime,
    :institution_value,
    :cost_basis,
    :quantity,
    :iso_currency_code,
    :unofficial_currency_code
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :security_id => String.t,
    :institution_price => float(),
    :institution_price_as_of => Date.t | nil,
    :institution_price_datetime => DateTime.t | nil,
    :institution_value => float(),
    :cost_basis => float() | nil,
    :quantity => float(),
    :iso_currency_code => String.t | nil,
    :unofficial_currency_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Holding do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:institution_price_as_of, :date, nil, options)
  end
end

