# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IdentityVerificationUserData do
  @moduledoc """
  The identity data that was either collected from the user or provided via API in order to perform an identity verification.
  """

  @derive [Poison.Encoder]
  defstruct [
    :phone_number,
    :date_of_birth,
    :ip_address,
    :email_address,
    :name,
    :address,
    :id_number
  ]

  @type t :: %__MODULE__{
    :phone_number => String.t | nil,
    :date_of_birth => Date.t | nil,
    :ip_address => String.t | nil,
    :email_address => String.t | nil,
    :name => ThePlaidAPI.Model.IdentityVerificationResponseUserName.t | nil,
    :address => ThePlaidAPI.Model.IdentityVerificationUserAddress.t | nil,
    :id_number => ThePlaidAPI.Model.UserIdNumber.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IdentityVerificationUserData do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date_of_birth, :date, nil, options)
    |> deserialize(:name, :struct, ThePlaidAPI.Model.IdentityVerificationResponseUserName, options)
    |> deserialize(:address, :struct, ThePlaidAPI.Model.IdentityVerificationUserAddress, options)
    |> deserialize(:id_number, :struct, ThePlaidAPI.Model.UserIdNumber, options)
  end
end

