# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IdentityVerificationListResponse do
  @moduledoc """
  Paginated list of Plaid sessions.
  """

  @derive [Poison.Encoder]
  defstruct [
    :identity_verifications,
    :next_cursor,
    :request_id
  ]

  @type t :: %__MODULE__{
    :identity_verifications => [ThePlaidAPI.Model.IdentityVerification.t],
    :next_cursor => String.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IdentityVerificationListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:identity_verifications, :list, ThePlaidAPI.Model.IdentityVerification, options)
  end
end

