# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IdentityVerificationUserAddress do
  @moduledoc """
  Even if an address has been collected, some fields may be null depending on the region's addressing system. For example:  Addresses from the United Kingdom will not include a region  Addresses from Hong Kong will not include postal code
  """

  @derive [Poison.Encoder]
  defstruct [
    :street,
    :street2,
    :city,
    :region,
    :postal_code,
    :country
  ]

  @type t :: %__MODULE__{
    :street => String.t | nil,
    :street2 => String.t | nil,
    :city => String.t | nil,
    :region => String.t | nil,
    :postal_code => String.t | nil,
    :country => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IdentityVerificationUserAddress do
  def decode(value, _options) do
    value
  end
end

