# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IncidentUpdate do
  @moduledoc """
  An update on the health incident
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :status,
    :updated_date
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :status => String.t | nil,
    :updated_date => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IncidentUpdate do
  def decode(value, _options) do
    value
  end
end

