# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IncomeVerificationTaxformsGetRequest do
  @moduledoc """
  IncomeVerificationTaxformsGetRequest defines the request schema for `/income/verification/taxforms/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :income_verification_id,
    :access_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :income_verification_id => String.t | nil,
    :access_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IncomeVerificationTaxformsGetRequest do
  def decode(value, _options) do
    value
  end
end

