# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IncomeVerificationTaxformsGetResponse do
  @moduledoc """
  IncomeVerificationTaxformsGetResponse defines the response schema for `/income/verification/taxforms/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :document_metadata,
    :taxforms,
    :error
  ]

  @type t :: %__MODULE__{
    :request_id => String.t | nil,
    :document_metadata => [ThePlaidAPI.Model.DocumentMetadata.t],
    :taxforms => [ThePlaidAPI.Model.Taxform.t],
    :error => ThePlaidAPI.Model.PlaidError.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IncomeVerificationTaxformsGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:document_metadata, :list, ThePlaidAPI.Model.DocumentMetadata, options)
    |> deserialize(:taxforms, :list, ThePlaidAPI.Model.Taxform, options)
    |> deserialize(:error, :struct, ThePlaidAPI.Model.PlaidError, options)
  end
end

