# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.IncomeVerificationPrecheckResponse do
  @moduledoc """
  IncomeVerificationPrecheckResponse defines the response schema for `/income/verification/precheck`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :precheck_id,
    :request_id,
    :confidence
  ]

  @type t :: %__MODULE__{
    :precheck_id => String.t,
    :request_id => String.t,
    :confidence => ThePlaidAPI.Model.IncomeVerificationPrecheckConfidence.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.IncomeVerificationPrecheckResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:confidence, :struct, ThePlaidAPI.Model.IncomeVerificationPrecheckConfidence, options)
  end
end

