# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.InstitutionsSearchResponse do
  @moduledoc """
  InstitutionsSearchResponse defines the response schema for `/institutions/search`
  """

  @derive [Poison.Encoder]
  defstruct [
    :institutions,
    :request_id
  ]

  @type t :: %__MODULE__{
    :institutions => [ThePlaidAPI.Model.Institution.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.InstitutionsSearchResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:institutions, :list, ThePlaidAPI.Model.Institution, options)
  end
end

