# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.InstitutionsSearchPaymentInitiationOptions do
  @moduledoc """
  Additional options that will be used to filter institutions by various Payment Initiation configurations.
  """

  @derive [Poison.Encoder]
  defstruct [
    :payment_id,
    :consent_id
  ]

  @type t :: %__MODULE__{
    :payment_id => String.t | nil,
    :consent_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.InstitutionsSearchPaymentInitiationOptions do
  def decode(value, _options) do
    value
  end
end

