# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.InstitutionsGetByIdRequestOptions do
  @moduledoc """
  Specifies optional parameters for `/institutions/get_by_id`. If provided, must not be `null`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :include_optional_metadata,
    :include_status,
    :include_auth_metadata,
    :include_payment_initiation_metadata
  ]

  @type t :: %__MODULE__{
    :include_optional_metadata => boolean() | nil,
    :include_status => boolean() | nil,
    :include_auth_metadata => boolean() | nil,
    :include_payment_initiation_metadata => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.InstitutionsGetByIdRequestOptions do
  def decode(value, _options) do
    value
  end
end

