# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemApplicationScopesUpdateRequest do
  @moduledoc """
  ItemApplicationScopesUpdateRequest defines the request schema for `/item/application/scopes/update`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token,
    :application_id,
    :scopes,
    :state,
    :context
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t,
    :application_id => String.t,
    :scopes => ThePlaidAPI.Model.Scopes.t,
    :state => String.t | nil,
    :context => ThePlaidAPI.Model.ScopesContext.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemApplicationScopesUpdateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:scopes, :struct, ThePlaidAPI.Model.Scopes, options)
    |> deserialize(:context, :struct, ThePlaidAPI.Model.ScopesContext, options)
  end
end

