# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemApplicationListResponse do
  @moduledoc """
  Describes the connected application for a particular end user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :applications
  ]

  @type t :: %__MODULE__{
    :request_id => String.t | nil,
    :applications => [ThePlaidAPI.Model.ConnectedApplication.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemApplicationListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:applications, :list, ThePlaidAPI.Model.ConnectedApplication, options)
  end
end

