# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemActivityListRequest do
  @moduledoc """
  Request to list a historical log of user consent events.
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token,
    :cursor,
    :count
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t | nil,
    :cursor => String.t | nil,
    :count => integer() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemActivityListRequest do
  def decode(value, _options) do
    value
  end
end

