# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemPublicTokenExchangeResponse do
  @moduledoc """
  ItemPublicTokenExchangeResponse defines the response schema for `/item/public_token/exchange`
  """

  @derive [Poison.Encoder]
  defstruct [
    :access_token,
    :item_id,
    :request_id
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :item_id => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemPublicTokenExchangeResponse do
  def decode(value, _options) do
    value
  end
end

