# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemImportRequestUserAuth do
  @moduledoc """
  Object of user ID and auth token pair, permitting Plaid to aggregate a user’s accounts
  """

  @derive [Poison.Encoder]
  defstruct [
    :user_id,
    :auth_token
  ]

  @type t :: %__MODULE__{
    :user_id => String.t,
    :auth_token => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemImportRequestUserAuth do
  def decode(value, _options) do
    value
  end
end

