# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemAccessTokenInvalidateRequest do
  @moduledoc """
  ItemAccessTokenInvalidateRequest defines the request schema for `/item/access_token/invalidate`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemAccessTokenInvalidateRequest do
  def decode(value, _options) do
    value
  end
end

