# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ItemStatusLastWebhook do
  @moduledoc """
  Information about the last webhook fired for the Item.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sent_at,
    :code_sent
  ]

  @type t :: %__MODULE__{
    :sent_at => DateTime.t | nil,
    :code_sent => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ItemStatusLastWebhook do
  def decode(value, _options) do
    value
  end
end

