# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LastDataAccessTimes do
  @moduledoc """
  Describes the last time each datatype was accessed by an application.
  """

  @derive [Poison.Encoder]
  defstruct [
    :application_id,
    :account_balance_info,
    :account_routing_number,
    :contact_details,
    :transactions,
    :credit_and_loans,
    :investments,
    :payroll_info,
    :transaction_risk_info
  ]

  @type t :: %__MODULE__{
    :application_id => String.t,
    :account_balance_info => DateTime.t | nil,
    :account_routing_number => DateTime.t | nil,
    :contact_details => DateTime.t | nil,
    :transactions => DateTime.t | nil,
    :credit_and_loans => DateTime.t | nil,
    :investments => DateTime.t | nil,
    :payroll_info => DateTime.t | nil,
    :transaction_risk_info => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LastDataAccessTimes do
  def decode(value, _options) do
    value
  end
end

