# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LiabilitiesObject do
  @moduledoc """
  An object containing liability accounts
  """

  @derive [Poison.Encoder]
  defstruct [
    :credit,
    :mortgage,
    :student
  ]

  @type t :: %__MODULE__{
    :credit => [ThePlaidAPI.Model.CreditCardLiability.t] | nil,
    :mortgage => [ThePlaidAPI.Model.MortgageLiability.t] | nil,
    :student => [ThePlaidAPI.Model.StudentLoan.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LiabilitiesObject do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:credit, :list, ThePlaidAPI.Model.CreditCardLiability, options)
    |> deserialize(:mortgage, :list, ThePlaidAPI.Model.MortgageLiability, options)
    |> deserialize(:student, :list, ThePlaidAPI.Model.StudentLoan, options)
  end
end

