# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestAccountSubtypes do
  @moduledoc """
  By default, Link will only display account types that are compatible with all products supplied in the `products` parameter of `/link/token/create`. You can further limit the accounts shown in Link by using `account_filters` to specify the account subtypes to be shown in Link. Only the specified subtypes will be shown. This filtering applies to both the Account Select view (if enabled) and the Institution Select view. Institutions that do not support the selected subtypes will be omitted from Link. To indicate that all subtypes should be shown, use the value `\"all\"`. If the `account_filters` filter is used, any account type for which a filter is not specified will be entirely omitted from Link.  For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#account-type-schema).  For institutions using OAuth, the filter will not affect the list of institutions or accounts shown by the bank in the OAuth window. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :depository,
    :credit,
    :loan,
    :investment
  ]

  @type t :: %__MODULE__{
    :depository => ThePlaidAPI.Model.LinkTokenCreateDepositoryFilter.t | nil,
    :credit => ThePlaidAPI.Model.LinkTokenCreateCreditFilter.t | nil,
    :loan => ThePlaidAPI.Model.LinkTokenCreateLoanFilter.t | nil,
    :investment => ThePlaidAPI.Model.LinkTokenCreateInvestmentFilter.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestAccountSubtypes do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:depository, :struct, ThePlaidAPI.Model.LinkTokenCreateDepositoryFilter, options)
    |> deserialize(:credit, :struct, ThePlaidAPI.Model.LinkTokenCreateCreditFilter, options)
    |> deserialize(:loan, :struct, ThePlaidAPI.Model.LinkTokenCreateLoanFilter, options)
    |> deserialize(:investment, :struct, ThePlaidAPI.Model.LinkTokenCreateInvestmentFilter, options)
  end
end

