# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateResponse do
  @moduledoc """
  LinkTokenCreateResponse defines the response schema for `/link/token/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :link_token,
    :expiration,
    :request_id
  ]

  @type t :: %__MODULE__{
    :link_token => String.t,
    :expiration => DateTime.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateResponse do
  def decode(value, _options) do
    value
  end
end

