# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenAccountFilters do
  @moduledoc """
  By default, Link will provide limited account filtering: it will only display Institutions that are compatible with all products supplied in the `products` parameter of `/link/token/create`, and, if `auth` is specified in the `products` array, will also filter out accounts other than `checking` and `savings` accounts on the Account Select pane. You can further limit the accounts shown in Link by using `account_filters` to specify the account subtypes to be shown in Link. Only the specified subtypes will be shown. This filtering applies to both the Account Select view (if enabled) and the Institution Select view. Institutions that do not support the selected subtypes will be omitted from Link. To indicate that all subtypes should be shown, use the value `\"all\"`. If the `account_filters` filter is used, any account type for which a filter is not specified will be entirely omitted from Link. For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#account-type-schema).  For institutions using OAuth, the filter will not affect the list of accounts shown by the bank in the OAuth window. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :depository,
    :credit,
    :loan,
    :investment
  ]

  @type t :: %__MODULE__{
    :depository => ThePlaidAPI.Model.DepositoryFilter.t | nil,
    :credit => ThePlaidAPI.Model.CreditFilter.t | nil,
    :loan => ThePlaidAPI.Model.LoanFilter.t | nil,
    :investment => ThePlaidAPI.Model.InvestmentFilter.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenAccountFilters do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:depository, :struct, ThePlaidAPI.Model.DepositoryFilter, options)
    |> deserialize(:credit, :struct, ThePlaidAPI.Model.CreditFilter, options)
    |> deserialize(:loan, :struct, ThePlaidAPI.Model.LoanFilter, options)
    |> deserialize(:investment, :struct, ThePlaidAPI.Model.InvestmentFilter, options)
  end
end

