# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestUserStatedIncomeSource do
  @moduledoc """
  Specifies user stated income sources for the Income product
  """

  @derive [Poison.Encoder]
  defstruct [
    :employer,
    :category,
    :pay_per_cycle,
    :pay_annual,
    :pay_type,
    :pay_frequency
  ]

  @type t :: %__MODULE__{
    :employer => String.t | nil,
    :category => ThePlaidAPI.Model.UserStatedIncomeSourceCategory.t | nil,
    :pay_per_cycle => float() | nil,
    :pay_annual => float() | nil,
    :pay_type => ThePlaidAPI.Model.UserStatedIncomeSourcePayType.t | nil,
    :pay_frequency => ThePlaidAPI.Model.UserStatedIncomeSourceFrequency.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestUserStatedIncomeSource do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:category, :struct, ThePlaidAPI.Model.UserStatedIncomeSourceCategory, options)
    |> deserialize(:pay_type, :struct, ThePlaidAPI.Model.UserStatedIncomeSourcePayType, options)
    |> deserialize(:pay_frequency, :struct, ThePlaidAPI.Model.UserStatedIncomeSourceFrequency, options)
  end
end

