# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkUserDeliveryStatusWebhook do
  @moduledoc """
  Webhook indicating that the status of the delivery of the hosted link session to a user
  """

  @derive [Poison.Encoder]
  defstruct [
    :webhook_type,
    :webhook_code,
    :link_delivery_session_id,
    :timestamp,
    :link_delivery_metadata
  ]

  @type t :: %__MODULE__{
    :webhook_type => String.t,
    :webhook_code => String.t,
    :link_delivery_session_id => String.t,
    :timestamp => String.t,
    :link_delivery_metadata => ThePlaidAPI.Model.LinkDeliveryMetadata.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkUserDeliveryStatusWebhook do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:link_delivery_metadata, :struct, ThePlaidAPI.Model.LinkDeliveryMetadata, options)
  end
end

