# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestEmploymentBankIncome do
  @moduledoc """
  Specifies options for initializing Link for use with Bank Employment. This field is required if `employment` is included in the `products` array and `bank` is specified in `employment_source_types`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :days_requested
  ]

  @type t :: %__MODULE__{
    :days_requested => integer()
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestEmploymentBankIncome do
  def decode(value, _options) do
    value
  end
end

