# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestDepositSwitch do
  @moduledoc """
  Specifies options for initializing Link for use with the Deposit Switch (beta) product. This field is required if `deposit_switch` is included in the `products` array.
  """

  @derive [Poison.Encoder]
  defstruct [
    :deposit_switch_id
  ]

  @type t :: %__MODULE__{
    :deposit_switch_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestDepositSwitch do
  def decode(value, _options) do
    value
  end
end

