# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenEuConfig do
  @moduledoc """
  Configuration parameters for EU flows
  """

  @derive [Poison.Encoder]
  defstruct [
    :headless
  ]

  @type t :: %__MODULE__{
    :headless => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenEuConfig do
  def decode(value, _options) do
    value
  end
end

