# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationBankIncome do
  @moduledoc """
  Specifies options for initializing Link for use with Bank Income. This field is required if `income_verification` is included in the `products` array and `bank` is specified in `income_source_types`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :days_requested,
    :enable_multiple_items
  ]

  @type t :: %__MODULE__{
    :days_requested => integer(),
    :enable_multiple_items => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationBankIncome do
  def decode(value, _options) do
    value
  end
end

