# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkDeliveryCommunicationMethod do
  @moduledoc """
  The communication method containing both the type and address to send the URL.
  """

  @derive [Poison.Encoder]
  defstruct [
    :method,
    :address
  ]

  @type t :: %__MODULE__{
    :method => ThePlaidAPI.Model.LinkDeliveryDeliveryMethod.t | nil,
    :address => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkDeliveryCommunicationMethod do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:method, :struct, ThePlaidAPI.Model.LinkDeliveryDeliveryMethod, options)
  end
end

