# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerification do
  @moduledoc """
  Specifies options for initializing Link for use with the Income product. This field is required if `income_verification` is included in the `products` array.
  """

  @derive [Poison.Encoder]
  defstruct [
    :income_verification_id,
    :asset_report_id,
    :precheck_id,
    :access_tokens,
    :income_source_types,
    :bank_income,
    :payroll_income,
    :stated_income_sources
  ]

  @type t :: %__MODULE__{
    :income_verification_id => String.t | nil,
    :asset_report_id => String.t | nil,
    :precheck_id => String.t | nil,
    :access_tokens => [ThePlaidAPI.Model.String.t] | nil,
    :income_source_types => [ThePlaidAPI.Model.IncomeVerificationSourceType.t] | nil,
    :bank_income => ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationBankIncome.t | nil,
    :payroll_income => ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationPayrollIncome.t | nil,
    :stated_income_sources => [ThePlaidAPI.Model.LinkTokenCreateRequestUserStatedIncomeSource.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerification do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:income_source_types, :list, ThePlaidAPI.Model.IncomeVerificationSourceType, options)
    |> deserialize(:bank_income, :struct, ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationBankIncome, options)
    |> deserialize(:payroll_income, :struct, ThePlaidAPI.Model.LinkTokenCreateRequestIncomeVerificationPayrollIncome, options)
    |> deserialize(:stated_income_sources, :list, ThePlaidAPI.Model.LinkTokenCreateRequestUserStatedIncomeSource, options)
  end
end

