# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkDeliveryMetadata do
  @moduledoc """
  Information related to the related to the delivery of the link session to users
  """

  @derive [Poison.Encoder]
  defstruct [
    :communication_method,
    :delivery_status
  ]

  @type t :: %__MODULE__{
    :communication_method => ThePlaidAPI.Model.LinkDeliveryWebhookCommunicationMethod.t | nil,
    :delivery_status => ThePlaidAPI.Model.LinkDeliveryWebhookDeliveryStatus.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkDeliveryMetadata do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:communication_method, :struct, ThePlaidAPI.Model.LinkDeliveryWebhookCommunicationMethod, options)
    |> deserialize(:delivery_status, :struct, ThePlaidAPI.Model.LinkDeliveryWebhookDeliveryStatus, options)
  end
end

