# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LinkTokenCreateRequestTransfer do
  @moduledoc """
  Specifies options for initializing Link for use with the Transfer product.
  """

  @derive [Poison.Encoder]
  defstruct [
    :intent_id,
    :payment_profile_token
  ]

  @type t :: %__MODULE__{
    :intent_id => String.t | nil,
    :payment_profile_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LinkTokenCreateRequestTransfer do
  def decode(value, _options) do
    value
  end
end

