# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.LoanIdentifiers do
  @moduledoc """
  Collection of current and previous identifiers for this loan.
  """

  @derive [Poison.Encoder]
  defstruct [
    :LOAN_IDENTIFIER
  ]

  @type t :: %__MODULE__{
    :LOAN_IDENTIFIER => ThePlaidAPI.Model.LoanIdentifier.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.LoanIdentifiers do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:LOAN_IDENTIFIER, :struct, ThePlaidAPI.Model.LoanIdentifier, options)
  end
end

