# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.MatchSummary do
  @moduledoc """
  Summary object reflecting the match result of the associated data
  """

  @derive [Poison.Encoder]
  defstruct [
    :summary
  ]

  @type t :: %__MODULE__{
    :summary => ThePlaidAPI.Model.MatchSummaryCode.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.MatchSummary do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:summary, :struct, ThePlaidAPI.Model.MatchSummaryCode, options)
  end
end

