# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Mfa do
  @moduledoc """
  Specifies the multi-factor authentication settings to use with this test account
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :question_rounds,
    :questions_per_round,
    :selection_rounds,
    :selections_per_question
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :question_rounds => float(),
    :questions_per_round => float(),
    :selection_rounds => float(),
    :selections_per_question => float()
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Mfa do
  def decode(value, _options) do
    value
  end
end

