# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.MultiDocumentRiskSignal do
  @moduledoc """
  Object containing risk signals and relevant metadata for a set of uploaded documents
  """

  @derive [Poison.Encoder]
  defstruct [
    :document_references,
    :risk_signals
  ]

  @type t :: %__MODULE__{
    :document_references => [ThePlaidAPI.Model.RiskSignalDocumentReference.t],
    :risk_signals => [ThePlaidAPI.Model.DocumentRiskSignal.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.MultiDocumentRiskSignal do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:document_references, :list, ThePlaidAPI.Model.RiskSignalDocumentReference, options)
    |> deserialize(:risk_signals, :list, ThePlaidAPI.Model.DocumentRiskSignal, options)
  end
end

