# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.NetPay do
  @moduledoc """
  An object representing information about the net pay amount on the paystub.
  """

  @derive [Poison.Encoder]
  defstruct [
    :current_amount,
    :description,
    :iso_currency_code,
    :unofficial_currency_code,
    :ytd_amount,
    :total
  ]

  @type t :: %__MODULE__{
    :current_amount => float() | nil,
    :description => String.t | nil,
    :iso_currency_code => String.t | nil,
    :unofficial_currency_code => String.t | nil,
    :ytd_amount => float() | nil,
    :total => ThePlaidAPI.Model.Total.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.NetPay do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:total, :struct, ThePlaidAPI.Model.Total, options)
  end
end

