# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.NumbersAch do
  @moduledoc """
  Identifying information for transferring money to or from a US account via ACH or wire transfer.
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :account,
    :routing,
    :wire_routing,
    :can_transfer_in,
    :can_transfer_out
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :account => String.t,
    :routing => String.t,
    :wire_routing => String.t | nil,
    :can_transfer_in => boolean() | nil,
    :can_transfer_out => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.NumbersAch do
  def decode(value, _options) do
    value
  end
end

