# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.NumbersBacsNullable do
  @moduledoc """
  Identifying information for transferring money to or from a UK bank account via BACS.
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :account,
    :sort_code
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :account => String.t,
    :sort_code => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.NumbersBacsNullable do
  def decode(value, _options) do
    value
  end
end

