# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.OverrideAccounts do
  @moduledoc """
  Data to use to set values of test accounts. Some values cannot be specified in the schema and will instead will be calculated from other test data in order to achieve more consistent, realistic test data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :subtype,
    :starting_balance,
    :force_available_balance,
    :currency,
    :meta,
    :numbers,
    :transactions,
    :holdings,
    :investment_transactions,
    :identity,
    :liability,
    :inflow_model,
    :income
  ]

  @type t :: %__MODULE__{
    :type => ThePlaidAPI.Model.OverrideAccountType.t,
    :subtype => ThePlaidAPI.Model.AccountSubtype.t | nil,
    :starting_balance => float(),
    :force_available_balance => float(),
    :currency => String.t,
    :meta => ThePlaidAPI.Model.Meta.t,
    :numbers => ThePlaidAPI.Model.Numbers.t,
    :transactions => [ThePlaidAPI.Model.TransactionOverride.t],
    :holdings => ThePlaidAPI.Model.HoldingsOverride.t | nil,
    :investment_transactions => ThePlaidAPI.Model.InvestmentsTransactionsOverride.t | nil,
    :identity => ThePlaidAPI.Model.OwnerOverride.t,
    :liability => ThePlaidAPI.Model.LiabilityOverride.t,
    :inflow_model => ThePlaidAPI.Model.InflowModel.t,
    :income => ThePlaidAPI.Model.IncomeOverride.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.OverrideAccounts do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.OverrideAccountType, options)
    |> deserialize(:subtype, :struct, ThePlaidAPI.Model.AccountSubtype, options)
    |> deserialize(:meta, :struct, ThePlaidAPI.Model.Meta, options)
    |> deserialize(:numbers, :struct, ThePlaidAPI.Model.Numbers, options)
    |> deserialize(:transactions, :list, ThePlaidAPI.Model.TransactionOverride, options)
    |> deserialize(:holdings, :struct, ThePlaidAPI.Model.HoldingsOverride, options)
    |> deserialize(:investment_transactions, :struct, ThePlaidAPI.Model.InvestmentsTransactionsOverride, options)
    |> deserialize(:identity, :struct, ThePlaidAPI.Model.OwnerOverride, options)
    |> deserialize(:liability, :struct, ThePlaidAPI.Model.LiabilityOverride, options)
    |> deserialize(:inflow_model, :struct, ThePlaidAPI.Model.InflowModel, options)
    |> deserialize(:income, :struct, ThePlaidAPI.Model.IncomeOverride, options)
  end
end

