# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerEndCustomerAddress do
  @moduledoc """
  The end customer's address.
  """

  @derive [Poison.Encoder]
  defstruct [
    :city,
    :street,
    :region,
    :postal_code,
    :country_code
  ]

  @type t :: %__MODULE__{
    :city => String.t | nil,
    :street => String.t | nil,
    :region => String.t | nil,
    :postal_code => String.t | nil,
    :country_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerEndCustomerAddress do
  def decode(value, _options) do
    value
  end
end

