# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerEndCustomerSecrets do
  @moduledoc """
  The secrets for the newly created end customer in non-Production environments.
  """

  @derive [Poison.Encoder]
  defstruct [
    :sandbox,
    :development
  ]

  @type t :: %__MODULE__{
    :sandbox => String.t | nil,
    :development => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerEndCustomerSecrets do
  def decode(value, _options) do
    value
  end
end

