# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerEndCustomerOAuthStatusUpdatedWebhook do
  @moduledoc """
  The webhook of type `PARTNER` and code `END_CUSTOMER_OAUTH_STATUS_UPDATED` will be fired when a partner's end customer has an update on their OAuth registration status with an institution.
  """

  @derive [Poison.Encoder]
  defstruct [
    :webhook_type,
    :webhook_code,
    :end_customer_client_id,
    :environment,
    :institution_id,
    :institution_name,
    :status
  ]

  @type t :: %__MODULE__{
    :webhook_type => String.t,
    :webhook_code => String.t,
    :end_customer_client_id => String.t,
    :environment => ThePlaidAPI.Model.WebhookEnvironmentValues.t,
    :institution_id => String.t,
    :institution_name => String.t,
    :status => ThePlaidAPI.Model.PartnerEndCustomerOAuthStatusUpdatedValues.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerEndCustomerOAuthStatusUpdatedWebhook do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:environment, :struct, ThePlaidAPI.Model.WebhookEnvironmentValues, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.PartnerEndCustomerOAuthStatusUpdatedValues, options)
  end
end

