# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerCustomerOAuthInstitutionsGetResponse do
  @moduledoc """
  Response schema for `/partner/customer/oauth_institutions/get`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :flowdown_status,
    :questionnaire_status,
    :institutions,
    :request_id
  ]

  @type t :: %__MODULE__{
    :flowdown_status => ThePlaidAPI.Model.PartnerEndCustomerFlowdownStatus.t | nil,
    :questionnaire_status => ThePlaidAPI.Model.PartnerEndCustomerQuestionnaireStatus.t | nil,
    :institutions => [ThePlaidAPI.Model.PartnerEndCustomerOAuthInstitution.t] | nil,
    :request_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerCustomerOAuthInstitutionsGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:flowdown_status, :struct, ThePlaidAPI.Model.PartnerEndCustomerFlowdownStatus, options)
    |> deserialize(:questionnaire_status, :struct, ThePlaidAPI.Model.PartnerEndCustomerQuestionnaireStatus, options)
    |> deserialize(:institutions, :list, ThePlaidAPI.Model.PartnerEndCustomerOAuthInstitution, options)
  end
end

