# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerEndCustomerAssetsUnderManagement do
  @moduledoc """
  Assets under management for the given end customer. Required for end customers with monthly service commitments.
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :iso_currency_code
  ]

  @type t :: %__MODULE__{
    :amount => float(),
    :iso_currency_code => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerEndCustomerAssetsUnderManagement do
  def decode(value, _options) do
    value
  end
end

