# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerCustomerCreateResponse do
  @moduledoc """
  Response schema for `/partner/customer/create`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :end_customer,
    :request_id
  ]

  @type t :: %__MODULE__{
    :end_customer => ThePlaidAPI.Model.PartnerEndCustomerWithSecrets.t | nil,
    :request_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerCustomerCreateResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:end_customer, :struct, ThePlaidAPI.Model.PartnerEndCustomerWithSecrets, options)
  end
end

