# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerCustomerOAuthInstitutionsGetRequest do
  @moduledoc """
  Request schema for `/partner/customer/oauth_institutions/get`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :end_customer_client_id
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :end_customer_client_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerCustomerOAuthInstitutionsGetRequest do
  def decode(value, _options) do
    value
  end
end

