# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Parties do
  @moduledoc """
  A collection of objects that define specific parties to a deal. This includes the direct participating parties, such as borrower and seller and the indirect parties such as the credit report provider.
  """

  @derive [Poison.Encoder]
  defstruct [
    :PARTY
  ]

  @type t :: %__MODULE__{
    :PARTY => [ThePlaidAPI.Model.Party.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Parties do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PARTY, :list, ThePlaidAPI.Model.Party, options)
  end
end

