# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerCustomerCreateRequest do
  @moduledoc """
  Request schema for `/partner/customer/create`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :company_name,
    :is_diligence_attested,
    :products,
    :create_link_customization,
    :logo,
    :legal_entity_name,
    :website,
    :application_name,
    :technical_contact,
    :billing_contact,
    :customer_support_info,
    :address,
    :is_bank_addendum_completed,
    :assets_under_management,
    :redirect_uris
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :company_name => String.t,
    :is_diligence_attested => boolean(),
    :products => [ThePlaidAPI.Model.Products.t],
    :create_link_customization => boolean() | nil,
    :logo => String.t | nil,
    :legal_entity_name => String.t,
    :website => String.t,
    :application_name => String.t,
    :technical_contact => ThePlaidAPI.Model.PartnerEndCustomerTechnicalContact.t | nil,
    :billing_contact => ThePlaidAPI.Model.PartnerEndCustomerBillingContact.t | nil,
    :customer_support_info => ThePlaidAPI.Model.PartnerEndCustomerCustomerSupportInfo.t | nil,
    :address => ThePlaidAPI.Model.PartnerEndCustomerAddress.t,
    :is_bank_addendum_completed => boolean(),
    :assets_under_management => ThePlaidAPI.Model.PartnerEndCustomerAssetsUnderManagement.t | nil,
    :redirect_uris => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerCustomerCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:products, :list, ThePlaidAPI.Model.Products, options)
    |> deserialize(:technical_contact, :struct, ThePlaidAPI.Model.PartnerEndCustomerTechnicalContact, options)
    |> deserialize(:billing_contact, :struct, ThePlaidAPI.Model.PartnerEndCustomerBillingContact, options)
    |> deserialize(:customer_support_info, :struct, ThePlaidAPI.Model.PartnerEndCustomerCustomerSupportInfo, options)
    |> deserialize(:address, :struct, ThePlaidAPI.Model.PartnerEndCustomerAddress, options)
    |> deserialize(:assets_under_management, :struct, ThePlaidAPI.Model.PartnerEndCustomerAssetsUnderManagement, options)
  end
end

