# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerEndCustomerWithSecretsAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :secrets
  ]

  @type t :: %__MODULE__{
    :secrets => ThePlaidAPI.Model.PartnerEndCustomerSecrets.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerEndCustomerWithSecretsAllOf do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:secrets, :struct, ThePlaidAPI.Model.PartnerEndCustomerSecrets, options)
  end
end

