# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PartnerCustomerGetResponse do
  @moduledoc """
  Response schema for `/partner/customer/get`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :end_customer,
    :request_id
  ]

  @type t :: %__MODULE__{
    :end_customer => ThePlaidAPI.Model.PartnerEndCustomer.t | nil,
    :request_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PartnerCustomerGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:end_customer, :struct, ThePlaidAPI.Model.PartnerEndCustomer, options)
  end
end

