# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Pay do
  @moduledoc """
  An object representing a monetary amount.
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :currency
  ]

  @type t :: %__MODULE__{
    :amount => float() | nil,
    :currency => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Pay do
  def decode(value, _options) do
    value
  end
end

