# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PayPeriodDetails do
  @moduledoc """
  Details about the pay period.
  """

  @derive [Poison.Encoder]
  defstruct [
    :check_amount,
    :distribution_breakdown,
    :end_date,
    :gross_earnings,
    :pay_date,
    :pay_frequency,
    :pay_day,
    :start_date
  ]

  @type t :: %__MODULE__{
    :check_amount => float() | nil,
    :distribution_breakdown => [ThePlaidAPI.Model.DistributionBreakdown.t] | nil,
    :end_date => Date.t | nil,
    :gross_earnings => float() | nil,
    :pay_date => Date.t | nil,
    :pay_frequency => String.t | nil,
    :pay_day => Date.t | nil,
    :start_date => Date.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PayPeriodDetails do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:distribution_breakdown, :list, ThePlaidAPI.Model.DistributionBreakdown, options)
    |> deserialize(:end_date, :date, nil, options)
    |> deserialize(:pay_date, :date, nil, options)
    |> deserialize(:pay_day, :date, nil, options)
    |> deserialize(:start_date, :date, nil, options)
  end
end

