# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PayStubTaxpayerId do
  @moduledoc """
  Taxpayer ID of the individual receiving the paystub.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id_type,
    :id_mask
  ]

  @type t :: %__MODULE__{
    :id_type => String.t | nil,
    :id_mask => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PayStubTaxpayerId do
  def decode(value, _options) do
    value
  end
end

