# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationPaymentListResponse do
  @moduledoc """
  PaymentInitiationPaymentListResponse defines the response schema for `/payment_initiation/payment/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :payments,
    :next_cursor,
    :request_id
  ]

  @type t :: %__MODULE__{
    :payments => [ThePlaidAPI.Model.PaymentInitiationPayment.t],
    :next_cursor => DateTime.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationPaymentListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:payments, :list, ThePlaidAPI.Model.PaymentInitiationPayment, options)
  end
end

