# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationPaymentGetResponse do
  @moduledoc """
  PaymentInitiationPaymentGetResponse defines the response schema for `/payment_initation/payment/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :payment_id,
    :amount,
    :status,
    :recipient_id,
    :reference,
    :adjusted_reference,
    :last_status_update,
    :schedule,
    :refund_details,
    :bacs,
    :iban,
    :refund_ids,
    :amount_refunded,
    :wallet_id,
    :scheme,
    :adjusted_scheme,
    :consent_id,
    :transaction_id,
    :request_id
  ]

  @type t :: %__MODULE__{
    :payment_id => String.t,
    :amount => ThePlaidAPI.Model.PaymentAmount.t,
    :status => ThePlaidAPI.Model.PaymentInitiationPaymentStatus.t,
    :recipient_id => String.t,
    :reference => String.t,
    :adjusted_reference => String.t | nil,
    :last_status_update => DateTime.t,
    :schedule => ThePlaidAPI.Model.ExternalPaymentScheduleGet.t | nil,
    :refund_details => ThePlaidAPI.Model.ExternalPaymentRefundDetails.t | nil,
    :bacs => ThePlaidAPI.Model.SenderBacsNullable.t | nil,
    :iban => String.t | nil,
    :refund_ids => [String.t] | nil,
    :amount_refunded => ThePlaidAPI.Model.PaymentAmountRefunded.t | nil,
    :wallet_id => String.t | nil,
    :scheme => ThePlaidAPI.Model.PaymentScheme.t | nil,
    :adjusted_scheme => ThePlaidAPI.Model.PaymentScheme.t | nil,
    :consent_id => String.t | nil,
    :transaction_id => String.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationPaymentGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:amount, :struct, ThePlaidAPI.Model.PaymentAmount, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.PaymentInitiationPaymentStatus, options)
    |> deserialize(:schedule, :struct, ThePlaidAPI.Model.ExternalPaymentScheduleGet, options)
    |> deserialize(:refund_details, :struct, ThePlaidAPI.Model.ExternalPaymentRefundDetails, options)
    |> deserialize(:bacs, :struct, ThePlaidAPI.Model.SenderBacsNullable, options)
    |> deserialize(:amount_refunded, :struct, ThePlaidAPI.Model.PaymentAmountRefunded, options)
    |> deserialize(:scheme, :struct, ThePlaidAPI.Model.PaymentScheme, options)
    |> deserialize(:adjusted_scheme, :struct, ThePlaidAPI.Model.PaymentScheme, options)
  end
end

