# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationOptionalRestrictionBacs do
  @moduledoc """
  An optional object used to restrict the accounts used for payments. If provided, the end user will be able to send payments only from the specified bank account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :account,
    :sort_code
  ]

  @type t :: %__MODULE__{
    :account => String.t | nil,
    :sort_code => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationOptionalRestrictionBacs do
  def decode(value, _options) do
    value
  end
end

