# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentProfileCreateResponse do
  @moduledoc """
  PaymentProfileCreateResponse defines the response schema for `/payment_profile/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :payment_profile_token,
    :request_id
  ]

  @type t :: %__MODULE__{
    :payment_profile_token => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentProfileCreateResponse do
  def decode(value, _options) do
    value
  end
end

