# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentConsentValidDateTime do
  @moduledoc """
  Life span for the payment consent. After the `to` date the payment consent expires and can no longer be used for payment initiation.
  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :to
  ]

  @type t :: %__MODULE__{
    :from => DateTime.t | nil,
    :to => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentConsentValidDateTime do
  def decode(value, _options) do
    value
  end
end

