# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationStandingOrderMetadata do
  @moduledoc """
  Metadata specifically related to valid Payment Initiation standing order configurations for the institution.
  """

  @derive [Poison.Encoder]
  defstruct [
    :supports_standing_order_end_date,
    :supports_standing_order_negative_execution_days,
    :valid_standing_order_intervals
  ]

  @type t :: %__MODULE__{
    :supports_standing_order_end_date => boolean(),
    :supports_standing_order_negative_execution_days => boolean(),
    :valid_standing_order_intervals => [ThePlaidAPI.Model.PaymentScheduleInterval.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationStandingOrderMetadata do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:valid_standing_order_intervals, :list, ThePlaidAPI.Model.PaymentScheduleInterval, options)
  end
end

