# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationPaymentCreateRequest do
  @moduledoc """
  PaymentInitiationPaymentCreateRequest defines the request schema for `/payment_initiation/payment/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :recipient_id,
    :reference,
    :amount,
    :schedule,
    :options
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :recipient_id => String.t,
    :reference => String.t,
    :amount => ThePlaidAPI.Model.PaymentAmount.t,
    :schedule => ThePlaidAPI.Model.ExternalPaymentScheduleRequest.t | nil,
    :options => ThePlaidAPI.Model.ExternalPaymentOptions.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationPaymentCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:amount, :struct, ThePlaidAPI.Model.PaymentAmount, options)
    |> deserialize(:schedule, :struct, ThePlaidAPI.Model.ExternalPaymentScheduleRequest, options)
    |> deserialize(:options, :struct, ThePlaidAPI.Model.ExternalPaymentOptions, options)
  end
end

