# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaymentInitiationPaymentListRequest do
  @moduledoc """
  PaymentInitiationPaymentListRequest defines the request schema for `/payment_initiation/payment/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :count,
    :cursor,
    :consent_id
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :count => integer() | nil,
    :cursor => DateTime.t | nil,
    :consent_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaymentInitiationPaymentListRequest do
  def decode(value, _options) do
    value
  end
end

