# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PayrollItemStatus do
  @moduledoc """
  Details about the status of the payroll item.
  """

  @derive [Poison.Encoder]
  defstruct [
    :processing_status
  ]

  @type t :: %__MODULE__{
    :processing_status => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PayrollItemStatus do
  def decode(value, _options) do
    value
  end
end

