# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PayrollItem do
  @moduledoc """
  An object containing information about the payroll item.
  """

  @derive [Poison.Encoder]
  defstruct [
    :item_id,
    :institution_id,
    :institution_name,
    :accounts,
    :payroll_income,
    :status,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :item_id => String.t,
    :institution_id => String.t,
    :institution_name => String.t,
    :accounts => [ThePlaidAPI.Model.PayrollIncomeAccountData.t],
    :payroll_income => [ThePlaidAPI.Model.PayrollIncomeObject.t],
    :status => ThePlaidAPI.Model.PayrollItemStatus.t | nil,
    :updated_at => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PayrollItem do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, ThePlaidAPI.Model.PayrollIncomeAccountData, options)
    |> deserialize(:payroll_income, :list, ThePlaidAPI.Model.PayrollIncomeObject, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.PayrollItemStatus, options)
  end
end

