# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PaystubDetails do
  @moduledoc """
  An object representing details that can be found on the paystub.
  """

  @derive [Poison.Encoder]
  defstruct [
    :pay_period_start_date,
    :pay_period_end_date,
    :pay_date,
    :paystub_provider,
    :pay_frequency
  ]

  @type t :: %__MODULE__{
    :pay_period_start_date => Date.t | nil,
    :pay_period_end_date => Date.t | nil,
    :pay_date => Date.t | nil,
    :paystub_provider => String.t | nil,
    :pay_frequency => ThePlaidAPI.Model.PaystubPayFrequency.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PaystubDetails do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:pay_period_start_date, :date, nil, options)
    |> deserialize(:pay_period_end_date, :date, nil, options)
    |> deserialize(:pay_date, :date, nil, options)
    |> deserialize(:pay_frequency, :struct, ThePlaidAPI.Model.PaystubPayFrequency, options)
  end
end

