# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PhoneNumber do
  @moduledoc """
  A phone number
  """

  @derive [Poison.Encoder]
  defstruct [
    :data,
    :primary,
    :type
  ]

  @type t :: %__MODULE__{
    :data => String.t,
    :primary => boolean(),
    :type => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PhoneNumber do
  def decode(value, _options) do
    value
  end
end

