# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PhoneNumberMatchScore do
  @moduledoc """
  Score found by matching phone number provided by the API with the phone number on the account at the financial institution. 100 is a perfect match and 0 is a no match. If the account contains multiple owners, the maximum match score is filled.
  """

  @derive [Poison.Encoder]
  defstruct [
    :score
  ]

  @type t :: %__MODULE__{
    :score => integer() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PhoneNumberMatchScore do
  def decode(value, _options) do
    value
  end
end

