# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PhysicalDocumentImages do
  @moduledoc """
  URLs for downloading original and cropped images for this document submission. The URLs are designed to only allow downloading, not hot linking, so the URL will only serve the document image for 60 seconds before expiring. The expiration time is 60 seconds after the `GET` request for the associated Identity Verification attempt. A new expiring URL is generated with each request, so you can always rerequest the Identity Verification attempt if one of your URLs expires.
  """

  @derive [Poison.Encoder]
  defstruct [
    :original_front,
    :original_back,
    :cropped_front,
    :cropped_back,
    :face
  ]

  @type t :: %__MODULE__{
    :original_front => String.t | nil,
    :original_back => String.t | nil,
    :cropped_front => String.t | nil,
    :cropped_back => String.t | nil,
    :face => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PhysicalDocumentImages do
  def decode(value, _options) do
    value
  end
end

