# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.PhysicalDocumentExtractedDataAnalysis do
  @moduledoc """
  Analysis of the data extracted from the submitted document.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :date_of_birth,
    :expiration_date,
    :issuing_country
  ]

  @type t :: %__MODULE__{
    :name => ThePlaidAPI.Model.DocumentNameMatchCode.t,
    :date_of_birth => ThePlaidAPI.Model.DocumentDateOfBirthMatchCode.t,
    :expiration_date => ThePlaidAPI.Model.ExpirationDate.t,
    :issuing_country => ThePlaidAPI.Model.IssuingCountry.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.PhysicalDocumentExtractedDataAnalysis do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:name, :struct, ThePlaidAPI.Model.DocumentNameMatchCode, options)
    |> deserialize(:date_of_birth, :struct, ThePlaidAPI.Model.DocumentDateOfBirthMatchCode, options)
    |> deserialize(:expiration_date, :struct, ThePlaidAPI.Model.ExpirationDate, options)
    |> deserialize(:issuing_country, :struct, ThePlaidAPI.Model.IssuingCountry, options)
  end
end

