# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProcessorStripeBankAccountTokenCreateResponse do
  @moduledoc """
  ProcessorStripeBankAccountTokenCreateResponse defines the response schema for `/processor/stripe/bank_account/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :stripe_bank_account_token,
    :request_id
  ]

  @type t :: %__MODULE__{
    :stripe_bank_account_token => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProcessorStripeBankAccountTokenCreateResponse do
  def decode(value, _options) do
    value
  end
end

