# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProcessorIdentityGetRequest do
  @moduledoc """
  ProcessorIdentityGetRequest defines the request schema for `/processor/identity/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :processor_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :processor_token => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProcessorIdentityGetRequest do
  def decode(value, _options) do
    value
  end
end

