# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProcessorSignalEvaluateResponse do
  @moduledoc """
  ProcessorSignalEvaluateResponse defines the response schema for `/processor/signal/evaluate`
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :scores,
    :core_attributes
  ]

  @type t :: %__MODULE__{
    :request_id => String.t,
    :scores => ThePlaidAPI.Model.SignalScores.t,
    :core_attributes => ThePlaidAPI.Model.SignalEvaluateCoreAttributes.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProcessorSignalEvaluateResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:scores, :struct, ThePlaidAPI.Model.SignalScores, options)
    |> deserialize(:core_attributes, :struct, ThePlaidAPI.Model.SignalEvaluateCoreAttributes, options)
  end
end

