# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProcessorAuthGetResponse do
  @moduledoc """
  ProcessorAuthGetResponse defines the response schema for `/processor/auth/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :numbers,
    :account
  ]

  @type t :: %__MODULE__{
    :request_id => String.t,
    :numbers => ThePlaidAPI.Model.ProcessorNumber.t,
    :account => ThePlaidAPI.Model.AccountBase.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProcessorAuthGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:numbers, :struct, ThePlaidAPI.Model.ProcessorNumber, options)
    |> deserialize(:account, :struct, ThePlaidAPI.Model.AccountBase, options)
  end
end

