# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProcessorTokenCreateResponse do
  @moduledoc """
  ProcessorTokenCreateResponse defines the response schema for `/processor/token/create` and `/processor/apex/processor_token/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :processor_token,
    :request_id
  ]

  @type t :: %__MODULE__{
    :processor_token => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProcessorTokenCreateResponse do
  def decode(value, _options) do
    value
  end
end

