# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ProductStatusBreakdown do
  @moduledoc """
  A detailed breakdown of the institution's performance for a request type. The values for `success`, `error_plaid`, and `error_institution` sum to 1. The time range used for calculating the breakdown may range from the most recent few minutes to the past six hours. In general, smaller institutions will show status that was calculated over a longer period of time. For Investment updates, which are refreshed less frequently, the period assessed may be 24 hours or more. For more details, see [Institution status details](https://plaid.com/docs/account/activity/#institution-status-details).
  """

  @derive [Poison.Encoder]
  defstruct [
    :success,
    :error_plaid,
    :error_institution,
    :refresh_interval
  ]

  @type t :: %__MODULE__{
    :success => float(),
    :error_plaid => float(),
    :error_institution => float(),
    :refresh_interval => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ProductStatusBreakdown do
  def decode(value, _options) do
    value
  end
end

