# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.RecurringTransfer do
  @moduledoc """
  Represents a recurring transfer within the Transfers API.
  """

  @derive [Poison.Encoder]
  defstruct [
    :recurring_transfer_id,
    :created,
    :next_origination_date,
    :test_clock_id,
    :type,
    :amount,
    :status,
    :ach_class,
    :network,
    :origination_account_id,
    :account_id,
    :funding_account_id,
    :iso_currency_code,
    :description,
    :transfer_ids,
    :user,
    :schedule
  ]

  @type t :: %__MODULE__{
    :recurring_transfer_id => String.t,
    :created => DateTime.t,
    :next_origination_date => Date.t,
    :test_clock_id => String.t | nil,
    :type => ThePlaidAPI.Model.TransferType.t,
    :amount => String.t,
    :status => ThePlaidAPI.Model.TransferRecurringStatus.t,
    :ach_class => ThePlaidAPI.Model.AchClass.t | nil,
    :network => ThePlaidAPI.Model.TransferNetwork.t,
    :origination_account_id => String.t,
    :account_id => String.t,
    :funding_account_id => String.t,
    :iso_currency_code => String.t,
    :description => String.t,
    :transfer_ids => [ThePlaidAPI.Model.String.t],
    :user => ThePlaidAPI.Model.TransferUserInResponse.t,
    :schedule => ThePlaidAPI.Model.TransferRecurringSchedule.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.RecurringTransfer do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:next_origination_date, :date, nil, options)
    |> deserialize(:type, :struct, ThePlaidAPI.Model.TransferType, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.TransferRecurringStatus, options)
    |> deserialize(:ach_class, :struct, ThePlaidAPI.Model.AchClass, options)
    |> deserialize(:network, :struct, ThePlaidAPI.Model.TransferNetwork, options)
    |> deserialize(:user, :struct, ThePlaidAPI.Model.TransferUserInResponse, options)
    |> deserialize(:schedule, :struct, ThePlaidAPI.Model.TransferRecurringSchedule, options)
  end
end

