# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.RiskCheckEmail do
  @moduledoc """
  Result summary object specifying values for `email` attributes of risk check.
  """

  @derive [Poison.Encoder]
  defstruct [
    :is_deliverable,
    :breach_count,
    :first_breached_at,
    :last_breached_at,
    :domain_registered_at,
    :domain_is_free_provider,
    :domain_is_custom,
    :domain_is_disposable,
    :top_level_domain_is_suspicious,
    :linked_services
  ]

  @type t :: %__MODULE__{
    :is_deliverable => ThePlaidAPI.Model.RiskCheckEmailIsDeliverableStatus.t,
    :breach_count => integer() | nil,
    :first_breached_at => Date.t | nil,
    :last_breached_at => Date.t | nil,
    :domain_registered_at => Date.t | nil,
    :domain_is_free_provider => ThePlaidAPI.Model.RiskCheckEmailDomainIsFreeProvider.t,
    :domain_is_custom => ThePlaidAPI.Model.RiskCheckEmailDomainIsCustom.t,
    :domain_is_disposable => ThePlaidAPI.Model.RiskCheckEmailDomainIsDisposable.t,
    :top_level_domain_is_suspicious => ThePlaidAPI.Model.RiskCheckEmailTopLevelDomainIsSuspicious.t,
    :linked_services => [ThePlaidAPI.Model.RiskCheckLinkedService.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.RiskCheckEmail do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:is_deliverable, :struct, ThePlaidAPI.Model.RiskCheckEmailIsDeliverableStatus, options)
    |> deserialize(:first_breached_at, :date, nil, options)
    |> deserialize(:last_breached_at, :date, nil, options)
    |> deserialize(:domain_registered_at, :date, nil, options)
    |> deserialize(:domain_is_free_provider, :struct, ThePlaidAPI.Model.RiskCheckEmailDomainIsFreeProvider, options)
    |> deserialize(:domain_is_custom, :struct, ThePlaidAPI.Model.RiskCheckEmailDomainIsCustom, options)
    |> deserialize(:domain_is_disposable, :struct, ThePlaidAPI.Model.RiskCheckEmailDomainIsDisposable, options)
    |> deserialize(:top_level_domain_is_suspicious, :struct, ThePlaidAPI.Model.RiskCheckEmailTopLevelDomainIsSuspicious, options)
    |> deserialize(:linked_services, :list, ThePlaidAPI.Model.RiskCheckLinkedService, options)
  end
end

