# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.RiskSignalDocumentReference do
  @moduledoc """
  Object containing metadata for the document
  """

  @derive [Poison.Encoder]
  defstruct [
    :document_id,
    :document_name
  ]

  @type t :: %__MODULE__{
    :document_id => String.t | nil,
    :document_name => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.RiskSignalDocumentReference do
  def decode(value, _options) do
    value
  end
end

