# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.RiskCheckBehavior do
  @moduledoc """
  Result summary object specifying values for `behavior` attributes of risk check, when available.
  """

  @derive [Poison.Encoder]
  defstruct [
    :user_interactions,
    :fraud_ring_detected,
    :bot_detected
  ]

  @type t :: %__MODULE__{
    :user_interactions => ThePlaidAPI.Model.RiskCheckBehaviorUserInteractionsLabel.t,
    :fraud_ring_detected => ThePlaidAPI.Model.RiskCheckBehaviorFraudRingDetectedLabel.t,
    :bot_detected => ThePlaidAPI.Model.RiskCheckBehaviorBotDetectedLabel.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.RiskCheckBehavior do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:user_interactions, :struct, ThePlaidAPI.Model.RiskCheckBehaviorUserInteractionsLabel, options)
    |> deserialize(:fraud_ring_detected, :struct, ThePlaidAPI.Model.RiskCheckBehaviorFraudRingDetectedLabel, options)
    |> deserialize(:bot_detected, :struct, ThePlaidAPI.Model.RiskCheckBehaviorBotDetectedLabel, options)
  end
end

