# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.RoleDetail do
  @moduledoc """
  Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
  """

  @derive [Poison.Encoder]
  defstruct [
    :PartyRoleType
  ]

  @type t :: %__MODULE__{
    :PartyRoleType => ThePlaidAPI.Model.PartyRoleType.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.RoleDetail do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PartyRoleType, :struct, ThePlaidAPI.Model.PartyRoleType, options)
  end
end

