# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxItemResetLoginResponse do
  @moduledoc """
  SandboxItemResetLoginResponse defines the response schema for `/sandbox/item/reset_login`
  """

  @derive [Poison.Encoder]
  defstruct [
    :reset_login,
    :request_id
  ]

  @type t :: %__MODULE__{
    :reset_login => boolean(),
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxItemResetLoginResponse do
  def decode(value, _options) do
    value
  end
end

