# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptions do
  @moduledoc """
  An optional set of options to be used when configuring the Item. If specified, must not be `null`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :webhook,
    :override_username,
    :override_password,
    :transactions,
    :income_verification
  ]

  @type t :: %__MODULE__{
    :webhook => String.t | nil,
    :override_username => String.t | nil,
    :override_password => String.t | nil,
    :transactions => ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsTransactions.t | nil,
    :income_verification => ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsIncomeVerification.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptions do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:transactions, :struct, ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsTransactions, options)
    |> deserialize(:income_verification, :struct, ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsIncomeVerification, options)
  end
end

