# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxItemSetVerificationStatusRequest do
  @moduledoc """
  SandboxItemSetVerificationStatusRequest defines the request schema for `/sandbox/item/set_verification_status`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token,
    :account_id,
    :verification_status
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t,
    :account_id => String.t,
    :verification_status => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxItemSetVerificationStatusRequest do
  def decode(value, _options) do
    value
  end
end

