# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxPublicTokenCreateRequest do
  @moduledoc """
  SandboxPublicTokenCreateRequest defines the request schema for `/sandbox/public_token/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :institution_id,
    :initial_products,
    :options,
    :user_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :institution_id => String.t,
    :initial_products => [ThePlaidAPI.Model.Products.t],
    :options => ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptions.t | nil,
    :user_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxPublicTokenCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:initial_products, :list, ThePlaidAPI.Model.Products, options)
    |> deserialize(:options, :struct, ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptions, options)
  end
end

