# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxOauthSelectAccountsRequest do
  @moduledoc """
  Defines the request schema for `sandbox/oauth/select_accounts`
  """

  @derive [Poison.Encoder]
  defstruct [
    :oauth_state_id,
    :accounts
  ]

  @type t :: %__MODULE__{
    :oauth_state_id => String.t,
    :accounts => [String.t]
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxOauthSelectAccountsRequest do
  def decode(value, _options) do
    value
  end
end

