# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxTransferSimulateRequest do
  @moduledoc """
  Defines the request schema for `/sandbox/transfer/simulate`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :transfer_id,
    :event_type,
    :failure_reason
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :transfer_id => String.t,
    :event_type => String.t,
    :failure_reason => ThePlaidAPI.Model.TransferFailure.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxTransferSimulateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:failure_reason, :struct, ThePlaidAPI.Model.TransferFailure, options)
  end
end

