# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsTransactions do
  @moduledoc """
  An optional set of parameters corresponding to transactions options.
  """

  @derive [Poison.Encoder]
  defstruct [
    :start_date,
    :end_date
  ]

  @type t :: %__MODULE__{
    :start_date => Date.t | nil,
    :end_date => Date.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxPublicTokenCreateRequestOptionsTransactions do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:start_date, :date, nil, options)
    |> deserialize(:end_date, :date, nil, options)
  end
end

