# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SandboxPublicTokenCreateResponse do
  @moduledoc """
  SandboxPublicTokenCreateResponse defines the response schema for `/sandbox/public_token/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :public_token,
    :request_id
  ]

  @type t :: %__MODULE__{
    :public_token => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SandboxPublicTokenCreateResponse do
  def decode(value, _options) do
    value
  end
end

