# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ScopesNullable do
  @moduledoc """
  The scopes object
  """

  @derive [Poison.Encoder]
  defstruct [
    :product_access,
    :accounts,
    :new_accounts
  ]

  @type t :: %__MODULE__{
    :product_access => ThePlaidAPI.Model.ProductAccess.t | nil,
    :accounts => [ThePlaidAPI.Model.AccountAccess.t] | nil,
    :new_accounts => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ScopesNullable do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:product_access, :struct, ThePlaidAPI.Model.ProductAccess, options)
    |> deserialize(:accounts, :list, ThePlaidAPI.Model.AccountAccess, options)
  end
end

