# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SecurityOverride do
  @moduledoc """
  Specify the security associated with the holding or investment transaction. When inputting custom security data to the Sandbox, Plaid will perform post-data-retrieval normalization and enrichment. These processes may cause the data returned by the Sandbox to be slightly different from the data you input. An ISO-4217 currency code and a security identifier (`ticker_symbol`, `cusip`, `isin`, or `sedol`) are required.
  """

  @derive [Poison.Encoder]
  defstruct [
    :isin,
    :cusip,
    :sedol,
    :name,
    :ticker_symbol,
    :currency
  ]

  @type t :: %__MODULE__{
    :isin => String.t | nil,
    :cusip => String.t | nil,
    :sedol => String.t | nil,
    :name => String.t | nil,
    :ticker_symbol => String.t | nil,
    :currency => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SecurityOverride do
  def decode(value, _options) do
    value
  end
end

