# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.ServiceProductFulfillment do
  @moduledoc """
  A collection of details related to a fulfillment service or product in terms of request, process and result.
  """

  @derive [Poison.Encoder]
  defstruct [
    :SERVICE_PRODUCT_FULFILLMENT_DETAIL
  ]

  @type t :: %__MODULE__{
    :SERVICE_PRODUCT_FULFILLMENT_DETAIL => ThePlaidAPI.Model.ServiceProductFulfillmentDetail.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.ServiceProductFulfillment do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SERVICE_PRODUCT_FULFILLMENT_DETAIL, :struct, ThePlaidAPI.Model.ServiceProductFulfillmentDetail, options)
  end
end

