# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SignalDevice do
  @moduledoc """
  Details about the end user's device
  """

  @derive [Poison.Encoder]
  defstruct [
    :ip_address,
    :user_agent
  ]

  @type t :: %__MODULE__{
    :ip_address => String.t | nil,
    :user_agent => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SignalDevice do
  def decode(value, _options) do
    value
  end
end

