# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.SignalScores do
  @moduledoc """
  Risk scoring details broken down by risk category.
  """

  @derive [Poison.Encoder]
  defstruct [
    :customer_initiated_return_risk,
    :bank_initiated_return_risk
  ]

  @type t :: %__MODULE__{
    :customer_initiated_return_risk => ThePlaidAPI.Model.CustomerInitiatedReturnRisk.t | nil,
    :bank_initiated_return_risk => ThePlaidAPI.Model.BankInitiatedReturnRisk.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.SignalScores do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:customer_initiated_return_risk, :struct, ThePlaidAPI.Model.CustomerInitiatedReturnRisk, options)
    |> deserialize(:bank_initiated_return_risk, :struct, ThePlaidAPI.Model.BankInitiatedReturnRisk, options)
  end
end

