# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Statuses do
  @moduledoc """
  A collection of STATUS containers.
  """

  @derive [Poison.Encoder]
  defstruct [
    :STATUS
  ]

  @type t :: %__MODULE__{
    :STATUS => ThePlaidAPI.Model.Status.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Statuses do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:STATUS, :struct, ThePlaidAPI.Model.Status, options)
  end
end

