# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.StudentLoan do
  @moduledoc """
  Contains details about a student loan account
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :account_number,
    :disbursement_dates,
    :expected_payoff_date,
    :guarantor,
    :interest_rate_percentage,
    :is_overdue,
    :last_payment_amount,
    :last_payment_date,
    :last_statement_issue_date,
    :loan_name,
    :loan_status,
    :minimum_payment_amount,
    :next_payment_due_date,
    :origination_date,
    :origination_principal_amount,
    :outstanding_interest_amount,
    :payment_reference_number,
    :pslf_status,
    :repayment_plan,
    :sequence_number,
    :servicer_address,
    :ytd_interest_paid,
    :ytd_principal_paid
  ]

  @type t :: %__MODULE__{
    :account_id => String.t | nil,
    :account_number => String.t | nil,
    :disbursement_dates => [Date.t] | nil,
    :expected_payoff_date => Date.t | nil,
    :guarantor => String.t | nil,
    :interest_rate_percentage => float(),
    :is_overdue => boolean() | nil,
    :last_payment_amount => float() | nil,
    :last_payment_date => Date.t | nil,
    :last_statement_issue_date => Date.t | nil,
    :loan_name => String.t | nil,
    :loan_status => ThePlaidAPI.Model.StudentLoanStatus.t,
    :minimum_payment_amount => float() | nil,
    :next_payment_due_date => Date.t | nil,
    :origination_date => Date.t | nil,
    :origination_principal_amount => float() | nil,
    :outstanding_interest_amount => float() | nil,
    :payment_reference_number => String.t | nil,
    :pslf_status => ThePlaidAPI.Model.PslfStatus.t,
    :repayment_plan => ThePlaidAPI.Model.StudentRepaymentPlan.t,
    :sequence_number => String.t | nil,
    :servicer_address => ThePlaidAPI.Model.ServicerAddressData.t,
    :ytd_interest_paid => float() | nil,
    :ytd_principal_paid => float() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.StudentLoan do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:disbursement_dates, :list, ThePlaidAPI.Model.Date, options)
    |> deserialize(:expected_payoff_date, :date, nil, options)
    |> deserialize(:last_payment_date, :date, nil, options)
    |> deserialize(:last_statement_issue_date, :date, nil, options)
    |> deserialize(:loan_status, :struct, ThePlaidAPI.Model.StudentLoanStatus, options)
    |> deserialize(:next_payment_due_date, :date, nil, options)
    |> deserialize(:origination_date, :date, nil, options)
    |> deserialize(:pslf_status, :struct, ThePlaidAPI.Model.PslfStatus, options)
    |> deserialize(:repayment_plan, :struct, ThePlaidAPI.Model.StudentRepaymentPlan, options)
    |> deserialize(:servicer_address, :struct, ThePlaidAPI.Model.ServicerAddressData, options)
  end
end

