# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TaxpayerIdentifiers do
  @moduledoc """
  The collection of TAXPAYER_IDENTIFICATION elements
  """

  @derive [Poison.Encoder]
  defstruct [
    :TAXPAYER_IDENTIFIER
  ]

  @type t :: %__MODULE__{
    :TAXPAYER_IDENTIFIER => ThePlaidAPI.Model.TaxpayerIdentifier.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TaxpayerIdentifiers do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TAXPAYER_IDENTIFIER, :struct, ThePlaidAPI.Model.TaxpayerIdentifier, options)
  end
end

