# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferQuestionnaireCreateResponse do
  @moduledoc """
  Defines the response schema for `/transfer/questionnaire/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :onboarding_url,
    :request_id
  ]

  @type t :: %__MODULE__{
    :onboarding_url => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferQuestionnaireCreateResponse do
  def decode(value, _options) do
    value
  end
end

