# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionsCategoryRule do
  @moduledoc """
  A representation of a transactions category rule.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :item_id,
    :created_at,
    :personal_finance_category,
    :rule_details
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :item_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :personal_finance_category => String.t | nil,
    :rule_details => ThePlaidAPI.Model.TransactionsRuleDetails.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionsCategoryRule do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rule_details, :struct, ThePlaidAPI.Model.TransactionsRuleDetails, options)
  end
end

