# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferIntentGetResponse do
  @moduledoc """
  Defines the response schema for `/transfer/intent/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :transfer_intent,
    :request_id
  ]

  @type t :: %__MODULE__{
    :transfer_intent => ThePlaidAPI.Model.TransferIntentGet.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferIntentGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:transfer_intent, :struct, ThePlaidAPI.Model.TransferIntentGet, options)
  end
end

