# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferOriginatorGetResponse do
  @moduledoc """
  Defines the response schema for `/transfer/originator/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :originator,
    :request_id
  ]

  @type t :: %__MODULE__{
    :originator => ThePlaidAPI.Model.DetailedOriginator.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferOriginatorGetResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:originator, :struct, ThePlaidAPI.Model.DetailedOriginator, options)
  end
end

