# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionsGetRequestOptions do
  @moduledoc """
  An optional object to be used with the request. If specified, `options` must not be `null`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :account_ids,
    :count,
    :offset,
    :include_original_description,
    :include_personal_finance_category_beta,
    :include_personal_finance_category,
    :include_logo_and_counterparty_beta
  ]

  @type t :: %__MODULE__{
    :account_ids => [String.t] | nil,
    :count => integer() | nil,
    :offset => integer() | nil,
    :include_original_description => boolean() | nil,
    :include_personal_finance_category_beta => boolean() | nil,
    :include_personal_finance_category => boolean() | nil,
    :include_logo_and_counterparty_beta => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionsGetRequestOptions do
  def decode(value, _options) do
    value
  end
end

