# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRefundCreateResponse do
  @moduledoc """
  Defines the response schema for `/transfer/refund/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :refund,
    :request_id
  ]

  @type t :: %__MODULE__{
    :refund => ThePlaidAPI.Model.TransferRefund.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRefundCreateResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:refund, :struct, ThePlaidAPI.Model.TransferRefund, options)
  end
end

