# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferCapabilitiesGetRtp do
  @moduledoc """
  Contains the supported service types in RTP
  """

  @derive [Poison.Encoder]
  defstruct [
    :credit
  ]

  @type t :: %__MODULE__{
    :credit => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferCapabilitiesGetRtp do
  def decode(value, _options) do
    value
  end
end

