# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferOriginatorListRequest do
  @moduledoc """
  Defines the request schema for `/transfer/originator/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :count,
    :offset
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :count => integer() | nil,
    :offset => integer() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferOriginatorListRequest do
  def decode(value, _options) do
    value
  end
end

