# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferQuestionnaireCreateRequest do
  @moduledoc """
  Defines the request schema for `/transfer/questionnaire/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :originator_client_id,
    :redirect_uri
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :originator_client_id => String.t,
    :redirect_uri => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferQuestionnaireCreateRequest do
  def decode(value, _options) do
    value
  end
end

