# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionOverride do
  @moduledoc """
  Data to populate as test transaction data. If not specified, random transactions will be generated instead.
  """

  @derive [Poison.Encoder]
  defstruct [
    :date_transacted,
    :date_posted,
    :amount,
    :description,
    :currency
  ]

  @type t :: %__MODULE__{
    :date_transacted => Date.t,
    :date_posted => Date.t,
    :amount => float(),
    :description => String.t,
    :currency => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionOverride do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:date_transacted, :date, nil, options)
    |> deserialize(:date_posted, :date, nil, options)
  end
end

