# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferDevice do
  @moduledoc """
  Information about the device being used to initiate the authorization.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ip_address,
    :user_agent
  ]

  @type t :: %__MODULE__{
    :ip_address => String.t,
    :user_agent => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferDevice do
  def decode(value, _options) do
    value
  end
end

