# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferFailure do
  @moduledoc """
  The failure reason if the event type for a transfer is `\"failed\"` or `\"returned\"`. Null value otherwise.
  """

  @derive [Poison.Encoder]
  defstruct [
    :ach_return_code,
    :description
  ]

  @type t :: %__MODULE__{
    :ach_return_code => String.t | nil,
    :description => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferFailure do
  def decode(value, _options) do
    value
  end
end

