# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferUserInRequest do
  @moduledoc """
  The legal name and other information for the account holder.
  """

  @derive [Poison.Encoder]
  defstruct [
    :legal_name,
    :phone_number,
    :email_address,
    :address
  ]

  @type t :: %__MODULE__{
    :legal_name => String.t,
    :phone_number => String.t | nil,
    :email_address => String.t | nil,
    :address => ThePlaidAPI.Model.TransferUserAddressInRequest.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferUserInRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:address, :struct, ThePlaidAPI.Model.TransferUserAddressInRequest, options)
  end
end

