# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRepaymentListResponse do
  @moduledoc """
  Defines the response schema for `/transfer/repayments/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :repayments,
    :request_id
  ]

  @type t :: %__MODULE__{
    :repayments => [ThePlaidAPI.Model.TransferRepayment.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRepaymentListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:repayments, :list, ThePlaidAPI.Model.TransferRepayment, options)
  end
end

