# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRepaymentReturnListResponse do
  @moduledoc """
  Defines the response schema for `/transfer/repayments/return/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :repayment_returns,
    :request_id
  ]

  @type t :: %__MODULE__{
    :repayment_returns => [ThePlaidAPI.Model.TransferRepaymentReturn.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRepaymentReturnListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:repayment_returns, :list, ThePlaidAPI.Model.TransferRepaymentReturn, options)
  end
end

