# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferIntentCreate do
  @moduledoc """
  Represents a transfer intent within Transfer UI.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :created,
    :status,
    :account_id,
    :origination_account_id,
    :funding_account_id,
    :amount,
    :mode,
    :network,
    :ach_class,
    :user,
    :description,
    :metadata,
    :iso_currency_code,
    :require_guarantee
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :created => DateTime.t,
    :status => ThePlaidAPI.Model.TransferIntentStatus.t,
    :account_id => String.t | nil,
    :origination_account_id => String.t,
    :funding_account_id => String.t,
    :amount => String.t,
    :mode => ThePlaidAPI.Model.TransferIntentCreateMode.t,
    :network => ThePlaidAPI.Model.TransferIntentCreateNetwork.t | nil,
    :ach_class => ThePlaidAPI.Model.AchClass.t | nil,
    :user => ThePlaidAPI.Model.TransferUserInResponse.t,
    :description => String.t,
    :metadata => %{optional(String.t) => String.t} | nil,
    :iso_currency_code => String.t,
    :require_guarantee => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferIntentCreate do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:status, :struct, ThePlaidAPI.Model.TransferIntentStatus, options)
    |> deserialize(:mode, :struct, ThePlaidAPI.Model.TransferIntentCreateMode, options)
    |> deserialize(:network, :struct, ThePlaidAPI.Model.TransferIntentCreateNetwork, options)
    |> deserialize(:ach_class, :struct, ThePlaidAPI.Model.AchClass, options)
    |> deserialize(:user, :struct, ThePlaidAPI.Model.TransferUserInResponse, options)
  end
end

