# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRecurringListResponse do
  @moduledoc """
  Defines the response schema for `/transfer/recurring/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :recurring_transfers,
    :request_id
  ]

  @type t :: %__MODULE__{
    :recurring_transfers => [ThePlaidAPI.Model.RecurringTransfer.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRecurringListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:recurring_transfers, :list, ThePlaidAPI.Model.RecurringTransfer, options)
  end
end

