# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRefundCreateRequest do
  @moduledoc """
  Defines the request schema for `/transfer/refund/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :transfer_id,
    :amount,
    :idempotency_key
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :transfer_id => String.t,
    :amount => String.t,
    :idempotency_key => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRefundCreateRequest do
  def decode(value, _options) do
    value
  end
end

