# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferMetricsGetResponse do
  @moduledoc """
  Defines the response schema for `/transfer/metrics/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :request_id,
    :daily_debit_transfer_volume,
    :daily_credit_transfer_volume,
    :monthly_transfer_volume,
    :iso_currency_code
  ]

  @type t :: %__MODULE__{
    :request_id => String.t,
    :daily_debit_transfer_volume => String.t,
    :daily_credit_transfer_volume => String.t,
    :monthly_transfer_volume => String.t,
    :iso_currency_code => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferMetricsGetResponse do
  def decode(value, _options) do
    value
  end
end

