# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferOriginatorCreateResponse do
  @moduledoc """
  Defines the response schema for `/transfer/originator/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :originator_client_id,
    :company_name,
    :request_id
  ]

  @type t :: %__MODULE__{
    :originator_client_id => String.t,
    :company_name => String.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferOriginatorCreateResponse do
  def decode(value, _options) do
    value
  end
end

