# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferExpectedSettlementScheduleItem do
  @moduledoc """
  Defines an expected sweep date and amount.
  """

  @derive [Poison.Encoder]
  defstruct [
    :settlement_date,
    :settled_amount
  ]

  @type t :: %__MODULE__{
    :settlement_date => Date.t,
    :settled_amount => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferExpectedSettlementScheduleItem do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:settlement_date, :date, nil, options)
  end
end

