# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionsRulesCreateRequest do
  @moduledoc """
  TransactionsRulesCreateRequest defines the request schema for `beta/transactions/rules/v1/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :access_token,
    :secret,
    :personal_finance_category,
    :rule_details
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :access_token => String.t,
    :secret => String.t | nil,
    :personal_finance_category => String.t,
    :rule_details => ThePlaidAPI.Model.TransactionsRuleDetails.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionsRulesCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rule_details, :struct, ThePlaidAPI.Model.TransactionsRuleDetails, options)
  end
end

