# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferRecurringCreateRequest do
  @moduledoc """
  Defines the request schema for `/transfer/recurring/create`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token,
    :idempotency_key,
    :account_id,
    :funding_account_id,
    :type,
    :network,
    :ach_class,
    :amount,
    :user_present,
    :iso_currency_code,
    :description,
    :test_clock_id,
    :schedule,
    :user,
    :device
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t,
    :idempotency_key => String.t,
    :account_id => String.t,
    :funding_account_id => String.t | nil,
    :type => ThePlaidAPI.Model.TransferType.t,
    :network => ThePlaidAPI.Model.TransferNetwork.t,
    :ach_class => ThePlaidAPI.Model.AchClass.t | nil,
    :amount => String.t,
    :user_present => boolean() | nil,
    :iso_currency_code => String.t | nil,
    :description => String.t,
    :test_clock_id => String.t | nil,
    :schedule => ThePlaidAPI.Model.TransferRecurringSchedule.t,
    :user => ThePlaidAPI.Model.TransferUserInRequest.t,
    :device => ThePlaidAPI.Model.TransferDevice.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferRecurringCreateRequest do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.TransferType, options)
    |> deserialize(:network, :struct, ThePlaidAPI.Model.TransferNetwork, options)
    |> deserialize(:ach_class, :struct, ThePlaidAPI.Model.AchClass, options)
    |> deserialize(:schedule, :struct, ThePlaidAPI.Model.TransferRecurringSchedule, options)
    |> deserialize(:user, :struct, ThePlaidAPI.Model.TransferUserInRequest, options)
    |> deserialize(:device, :struct, ThePlaidAPI.Model.TransferDevice, options)
  end
end

