# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferOriginatorListResponse do
  @moduledoc """
  Defines the response schema for `/transfer/originator/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :originators,
    :request_id
  ]

  @type t :: %__MODULE__{
    :originators => [ThePlaidAPI.Model.Originator.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferOriginatorListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:originators, :list, ThePlaidAPI.Model.Originator, options)
  end
end

