# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionsEnrichRequestOptions do
  @moduledoc """
  An optional object to be used with the request.
  """

  @derive [Poison.Encoder]
  defstruct [
    :include_legacy_category
  ]

  @type t :: %__MODULE__{
    :include_legacy_category => boolean() | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionsEnrichRequestOptions do
  def decode(value, _options) do
    value
  end
end

