# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferEvent do
  @moduledoc """
  Represents an event in the Transfers API.
  """

  @derive [Poison.Encoder]
  defstruct [
    :event_id,
    :timestamp,
    :event_type,
    :account_id,
    :funding_account_id,
    :transfer_id,
    :origination_account_id,
    :transfer_type,
    :transfer_amount,
    :failure_reason,
    :sweep_id,
    :sweep_amount,
    :refund_id,
    :originator_client_id
  ]

  @type t :: %__MODULE__{
    :event_id => integer(),
    :timestamp => DateTime.t,
    :event_type => ThePlaidAPI.Model.TransferEventType.t,
    :account_id => String.t,
    :funding_account_id => String.t,
    :transfer_id => String.t,
    :origination_account_id => String.t | nil,
    :transfer_type => ThePlaidAPI.Model.TransferType.t,
    :transfer_amount => String.t,
    :failure_reason => ThePlaidAPI.Model.TransferFailure.t | nil,
    :sweep_id => String.t | nil,
    :sweep_amount => String.t | nil,
    :refund_id => String.t | nil,
    :originator_client_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferEvent do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:event_type, :struct, ThePlaidAPI.Model.TransferEventType, options)
    |> deserialize(:transfer_type, :struct, ThePlaidAPI.Model.TransferType, options)
    |> deserialize(:failure_reason, :struct, ThePlaidAPI.Model.TransferFailure, options)
  end
end

