# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferListResponse do
  @moduledoc """
  Defines the response schema for `/transfer/list`
  """

  @derive [Poison.Encoder]
  defstruct [
    :transfers,
    :request_id
  ]

  @type t :: %__MODULE__{
    :transfers => [ThePlaidAPI.Model.Transfer.t],
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:transfers, :list, ThePlaidAPI.Model.Transfer, options)
  end
end

