# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferTestClock do
  @moduledoc """
  Defines the test clock for a transfer.
  """

  @derive [Poison.Encoder]
  defstruct [
    :test_clock_id,
    :virtual_time
  ]

  @type t :: %__MODULE__{
    :test_clock_id => String.t,
    :virtual_time => DateTime.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferTestClock do
  def decode(value, _options) do
    value
  end
end

