# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransactionAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :authorized_date,
    :authorized_datetime,
    :datetime,
    :payment_channel,
    :personal_finance_category,
    :transaction_code,
    :personal_finance_category_icon_url,
    :counterparties
  ]

  @type t :: %__MODULE__{
    :authorized_date => Date.t | nil,
    :authorized_datetime => DateTime.t | nil,
    :datetime => DateTime.t | nil,
    :payment_channel => String.t,
    :personal_finance_category => ThePlaidAPI.Model.PersonalFinanceCategory.t | nil,
    :transaction_code => ThePlaidAPI.Model.TransactionCode.t | nil,
    :personal_finance_category_icon_url => String.t | nil,
    :counterparties => [ThePlaidAPI.Model.TransactionCounterparty.t] | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransactionAllOf do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:authorized_date, :date, nil, options)
    |> deserialize(:personal_finance_category, :struct, ThePlaidAPI.Model.PersonalFinanceCategory, options)
    |> deserialize(:transaction_code, :struct, ThePlaidAPI.Model.TransactionCode, options)
    |> deserialize(:counterparties, :list, ThePlaidAPI.Model.TransactionCounterparty, options)
  end
end

