# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.TransferCapabilitiesGetRequest do
  @moduledoc """
  Defines the request schema for `/transfer/capabilities/get`
  """

  @derive [Poison.Encoder]
  defstruct [
    :client_id,
    :secret,
    :access_token,
    :account_id,
    :payment_profile_token
  ]

  @type t :: %__MODULE__{
    :client_id => String.t | nil,
    :secret => String.t | nil,
    :access_token => String.t | nil,
    :account_id => String.t | nil,
    :payment_profile_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.TransferCapabilitiesGetRequest do
  def decode(value, _options) do
    value
  end
end

