# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.UserCustomPassword do
  @moduledoc """
  Custom test accounts are configured with a JSON configuration object formulated according to the schema below. All top level fields are optional. Sending an empty object as a configuration will result in an account configured with random balances and transaction history.
  """

  @derive [Poison.Encoder]
  defstruct [
    :version,
    :seed,
    :override_accounts,
    :mfa,
    :recaptcha,
    :force_error
  ]

  @type t :: %__MODULE__{
    :version => String.t | nil,
    :seed => String.t,
    :override_accounts => [ThePlaidAPI.Model.OverrideAccounts.t],
    :mfa => ThePlaidAPI.Model.Mfa.t,
    :recaptcha => String.t,
    :force_error => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.UserCustomPassword do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:override_accounts, :list, ThePlaidAPI.Model.OverrideAccounts, options)
    |> deserialize(:mfa, :struct, ThePlaidAPI.Model.Mfa, options)
  end
end

