# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.UserAddress do
  @moduledoc """
  Home address for the user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :street,
    :street2,
    :city,
    :region,
    :postal_code,
    :country
  ]

  @type t :: %__MODULE__{
    :street => String.t,
    :street2 => String.t | nil,
    :city => String.t,
    :region => String.t,
    :postal_code => String.t,
    :country => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.UserAddress do
  def decode(value, _options) do
    value
  end
end

