# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.UserIdNumber do
  @moduledoc """
  ID number submitted by the user, currently used only for the Identity Verification product. If the user has not submitted this data yet, this field will be `null`. Otherwise, both fields are guaranteed to be filled.
  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :type
  ]

  @type t :: %__MODULE__{
    :value => String.t,
    :type => ThePlaidAPI.Model.IdNumberType.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.UserIdNumber do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.IdNumberType, options)
  end
end

