# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.W2StateAndLocalWages do
  @moduledoc """
  W2 state and local wages
  """

  @derive [Poison.Encoder]
  defstruct [
    :state,
    :employer_state_id_number,
    :state_wages_tips,
    :state_income_tax,
    :local_wages_tips,
    :local_income_tax,
    :locality_name
  ]

  @type t :: %__MODULE__{
    :state => String.t | nil,
    :employer_state_id_number => String.t | nil,
    :state_wages_tips => String.t | nil,
    :state_income_tax => String.t | nil,
    :local_wages_tips => String.t | nil,
    :local_income_tax => String.t | nil,
    :locality_name => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.W2StateAndLocalWages do
  def decode(value, _options) do
    value
  end
end

