# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WalletTransactionStatusUpdateWebhook do
  @moduledoc """
  Fired when the status of a wallet transaction has changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :webhook_type,
    :webhook_code,
    :transaction_id,
    :payment_id,
    :wallet_id,
    :new_status,
    :old_status,
    :timestamp,
    :environment
  ]

  @type t :: %__MODULE__{
    :webhook_type => String.t,
    :webhook_code => String.t,
    :transaction_id => String.t,
    :payment_id => String.t | nil,
    :wallet_id => String.t | nil,
    :new_status => ThePlaidAPI.Model.WalletTransactionStatus.t,
    :old_status => ThePlaidAPI.Model.WalletTransactionStatus.t,
    :timestamp => DateTime.t,
    :environment => ThePlaidAPI.Model.WebhookEnvironmentValues.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WalletTransactionStatusUpdateWebhook do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:new_status, :struct, ThePlaidAPI.Model.WalletTransactionStatus, options)
    |> deserialize(:old_status, :struct, ThePlaidAPI.Model.WalletTransactionStatus, options)
    |> deserialize(:environment, :struct, ThePlaidAPI.Model.WebhookEnvironmentValues, options)
  end
end

