# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WalletTransaction do
  @moduledoc """
  The transaction details
  """

  @derive [Poison.Encoder]
  defstruct [
    :transaction_id,
    :wallet_id,
    :reference,
    :type,
    :amount,
    :counterparty,
    :status,
    :created_at,
    :last_status_update,
    :payment_id
  ]

  @type t :: %__MODULE__{
    :transaction_id => String.t,
    :wallet_id => String.t,
    :reference => String.t,
    :type => String.t,
    :amount => ThePlaidAPI.Model.WalletTransactionAmount.t,
    :counterparty => ThePlaidAPI.Model.WalletTransactionCounterparty.t,
    :status => ThePlaidAPI.Model.WalletTransactionStatus.t,
    :created_at => DateTime.t,
    :last_status_update => DateTime.t,
    :payment_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WalletTransaction do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:amount, :struct, ThePlaidAPI.Model.WalletTransactionAmount, options)
    |> deserialize(:counterparty, :struct, ThePlaidAPI.Model.WalletTransactionCounterparty, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.WalletTransactionStatus, options)
  end
end

