# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.Warning do
  @moduledoc """
  It is possible for an Asset Report to be returned with missing account owner information. In such cases, the Asset Report will contain warning data in the response, indicating why obtaining the owner information failed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :warning_type,
    :warning_code,
    :cause
  ]

  @type t :: %__MODULE__{
    :warning_type => String.t,
    :warning_code => String.t,
    :cause => ThePlaidAPI.Model.Cause.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.Warning do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:cause, :struct, ThePlaidAPI.Model.Cause, options)
  end
end

