# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningIndividualHitListResponse do
  @moduledoc """
  Paginated list of individual watchlist screening hits
  """

  @derive [Poison.Encoder]
  defstruct [
    :watchlist_screening_hits,
    :next_cursor,
    :request_id
  ]

  @type t :: %__MODULE__{
    :watchlist_screening_hits => [ThePlaidAPI.Model.WatchlistScreeningHit.t],
    :next_cursor => String.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningIndividualHitListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:watchlist_screening_hits, :list, ThePlaidAPI.Model.WatchlistScreeningHit, options)
  end
end

