# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningHitLocations do
  @moduledoc """
  Location information for the associated individual watchlist hit
  """

  @derive [Poison.Encoder]
  defstruct [
    :full,
    :country
  ]

  @type t :: %__MODULE__{
    :full => String.t,
    :country => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningHitLocations do
  def decode(value, _options) do
    value
  end
end

