# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningIndividualProgramListRequest do
  @moduledoc """
  Request input for listing watchlist screening programs for individuals
  """

  @derive [Poison.Encoder]
  defstruct [
    :secret,
    :client_id,
    :cursor
  ]

  @type t :: %__MODULE__{
    :secret => String.t | nil,
    :client_id => String.t | nil,
    :cursor => String.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningIndividualProgramListRequest do
  def decode(value, _options) do
    value
  end
end

