# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningIndividualReviewListResponse do
  @moduledoc """
  Paginated list of screening reviews
  """

  @derive [Poison.Encoder]
  defstruct [
    :watchlist_screening_reviews,
    :next_cursor,
    :request_id
  ]

  @type t :: %__MODULE__{
    :watchlist_screening_reviews => [ThePlaidAPI.Model.WatchlistScreeningReview.t],
    :next_cursor => String.t | nil,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningIndividualReviewListResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:watchlist_screening_reviews, :list, ThePlaidAPI.Model.WatchlistScreeningReview, options)
  end
end

