# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningIndividualUpdateResponse do
  @moduledoc """
  The screening object allows you to represent a customer in your system, update their profile, and search for them on various watchlists. Note: Rejected customers will not receive new hits, regardless of program configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :search_terms,
    :assignee,
    :status,
    :client_user_id,
    :audit_trail,
    :request_id
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :search_terms => ThePlaidAPI.Model.WatchlistScreeningSearchTerms.t,
    :assignee => String.t | nil,
    :status => ThePlaidAPI.Model.WatchlistScreeningStatus.t,
    :client_user_id => String.t | nil,
    :audit_trail => ThePlaidAPI.Model.WatchlistScreeningAuditTrail.t,
    :request_id => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningIndividualUpdateResponse do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:search_terms, :struct, ThePlaidAPI.Model.WatchlistScreeningSearchTerms, options)
    |> deserialize(:status, :struct, ThePlaidAPI.Model.WatchlistScreeningStatus, options)
    |> deserialize(:audit_trail, :struct, ThePlaidAPI.Model.WatchlistScreeningAuditTrail, options)
  end
end

