# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningDocument do
  @moduledoc """
  An official document, usually issued by a governing body or institution, with an associated identifier.
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :number
  ]

  @type t :: %__MODULE__{
    :type => ThePlaidAPI.Model.WatchlistScreeningDocumentType.t,
    :number => String.t
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningDocument do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ThePlaidAPI.Model.WatchlistScreeningDocumentType, options)
  end
end

