# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ThePlaidAPI.Model.WatchlistScreeningHit do
  @moduledoc """
  Data from a government watchlist or PEP list that has been attached to the screening.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :review_status,
    :first_active,
    :inactive_since,
    :historical_since,
    :list_code,
    :plaid_uid,
    :source_uid,
    :analysis,
    :data
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :review_status => ThePlaidAPI.Model.WatchlistScreeningHitStatus.t,
    :first_active => DateTime.t,
    :inactive_since => DateTime.t | nil,
    :historical_since => DateTime.t | nil,
    :list_code => ThePlaidAPI.Model.IndividualWatchlistCode.t,
    :plaid_uid => String.t,
    :source_uid => String.t | nil,
    :analysis => ThePlaidAPI.Model.ScreeningHitAnalysis.t | nil,
    :data => ThePlaidAPI.Model.ScreeningHitData.t | nil
  }
end

defimpl Poison.Decoder, for: ThePlaidAPI.Model.WatchlistScreeningHit do
  import ThePlaidAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:review_status, :struct, ThePlaidAPI.Model.WatchlistScreeningHitStatus, options)
    |> deserialize(:list_code, :struct, ThePlaidAPI.Model.IndividualWatchlistCode, options)
    |> deserialize(:analysis, :struct, ThePlaidAPI.Model.ScreeningHitAnalysis, options)
    |> deserialize(:data, :struct, ThePlaidAPI.Model.ScreeningHitData, options)
  end
end

