# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateModerationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :model,
    :results
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :model => String.t,
    :results => [OpenAIAPI.Model.CreateModerationResponseResultsInner.t]
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateModerationResponse do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:results, :list, OpenAIAPI.Model.CreateModerationResponseResultsInner, options)
  end
end

