# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateAnswerResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :object,
    :model,
    :search_model,
    :completion,
    :answers,
    :selected_documents
  ]

  @type t :: %__MODULE__{
    :object => String.t | nil,
    :model => String.t | nil,
    :search_model => String.t | nil,
    :completion => String.t | nil,
    :answers => [String.t] | nil,
    :selected_documents => [OpenAIAPI.Model.CreateAnswerResponseSelectedDocumentsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateAnswerResponse do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:selected_documents, :list, OpenAIAPI.Model.CreateAnswerResponseSelectedDocumentsInner, options)
  end
end

