# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateEmbeddingResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :object,
    :model,
    :data,
    :usage
  ]

  @type t :: %__MODULE__{
    :object => String.t,
    :model => String.t,
    :data => [OpenAIAPI.Model.CreateEmbeddingResponseDataInner.t],
    :usage => OpenAIAPI.Model.CreateEmbeddingResponseUsage.t
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateEmbeddingResponse do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :list, OpenAIAPI.Model.CreateEmbeddingResponseDataInner, options)
    |> deserialize(:usage, :struct, OpenAIAPI.Model.CreateEmbeddingResponseUsage, options)
  end
end

