# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateCompletionResponseUsage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :prompt_tokens,
    :completion_tokens,
    :total_tokens
  ]

  @type t :: %__MODULE__{
    :prompt_tokens => integer(),
    :completion_tokens => integer(),
    :total_tokens => integer()
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateCompletionResponseUsage do
  def decode(value, _options) do
    value
  end
end

