# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateChatCompletionResponseChoicesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :index,
    :message,
    :finish_reason
  ]

  @type t :: %__MODULE__{
    :index => integer() | nil,
    :message => OpenAIAPI.Model.ChatCompletionResponseMessage.t | nil,
    :finish_reason => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateChatCompletionResponseChoicesInner do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:message, :struct, OpenAIAPI.Model.ChatCompletionResponseMessage, options)
  end
end

