# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateSearchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :object,
    :model,
    :data
  ]

  @type t :: %__MODULE__{
    :object => String.t | nil,
    :model => String.t | nil,
    :data => [OpenAIAPI.Model.CreateSearchResponseDataInner.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateSearchResponse do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:data, :list, OpenAIAPI.Model.CreateSearchResponseDataInner, options)
  end
end

