# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateCompletionRequestStop do
  @moduledoc """
  Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateCompletionRequestStop do
  def decode(value, _options) do
    value
  end
end

