# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateEditRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :model,
    :input,
    :instruction,
    :n,
    :temperature,
    :top_p
  ]

  @type t :: %__MODULE__{
    :model => String.t,
    :input => String.t | nil,
    :instruction => String.t,
    :n => integer() | nil,
    :temperature => float() | nil,
    :top_p => float() | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateEditRequest do
  def decode(value, _options) do
    value
  end
end

