# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateTranslationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :text
  ]

  @type t :: %__MODULE__{
    :text => String.t
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateTranslationResponse do
  def decode(value, _options) do
    value
  end
end

