# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateModerationRequestInput do
  @moduledoc """
  The input text to classify
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateModerationRequestInput do
  def decode(value, _options) do
    value
  end
end

