# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.CreateEditResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :object,
    :created,
    :choices,
    :usage
  ]

  @type t :: %__MODULE__{
    :object => String.t,
    :created => integer(),
    :choices => [OpenAIAPI.Model.CreateCompletionResponseChoicesInner.t],
    :usage => OpenAIAPI.Model.CreateCompletionResponseUsage.t
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.CreateEditResponse do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:choices, :list, OpenAIAPI.Model.CreateCompletionResponseChoicesInner, options)
    |> deserialize(:usage, :struct, OpenAIAPI.Model.CreateCompletionResponseUsage, options)
  end
end

