# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.Engine do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :object,
    :created,
    :ready
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :object => String.t,
    :created => integer() | nil,
    :ready => boolean()
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.Engine do
  def decode(value, _options) do
    value
  end
end

