# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.FineTune do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :object,
    :created_at,
    :updated_at,
    :model,
    :fine_tuned_model,
    :organization_id,
    :status,
    :hyperparams,
    :training_files,
    :validation_files,
    :result_files,
    :events
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :object => String.t,
    :created_at => integer(),
    :updated_at => integer(),
    :model => String.t,
    :fine_tuned_model => String.t | nil,
    :organization_id => String.t,
    :status => String.t,
    :hyperparams => map(),
    :training_files => [OpenAIAPI.Model.OpenAiFile.t],
    :validation_files => [OpenAIAPI.Model.OpenAiFile.t],
    :result_files => [OpenAIAPI.Model.OpenAiFile.t],
    :events => [OpenAIAPI.Model.FineTuneEvent.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.FineTune do
  import OpenAIAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:training_files, :list, OpenAIAPI.Model.OpenAiFile, options)
    |> deserialize(:validation_files, :list, OpenAIAPI.Model.OpenAiFile, options)
    |> deserialize(:result_files, :list, OpenAIAPI.Model.OpenAiFile, options)
    |> deserialize(:events, :list, OpenAIAPI.Model.FineTuneEvent, options)
  end
end

