# NOTE: This file is auto generated by OpenAPI Generator 6.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenAIAPI.Model.ImagesResponseDataInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :b64_json
  ]

  @type t :: %__MODULE__{
    :url => String.t | nil,
    :b64_json => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenAIAPI.Model.ImagesResponseDataInner do
  def decode(value, _options) do
    value
  end
end

